SELECT * FROM feed WHERE checked + refresh < 0;
SELECT * FROM feed;
SELECT * FROM item ORDER BY timestamp DESC, iid DESC; -- WHERE ". implode(" OR ", $where) ." 
SELECT * FROM item WHERE fid = 0 ORDER BY timestamp DESC, iid DESC;
SELECT * FROM bundle ORDER BY title;
SELECT * FROM feed ORDER BY fid;
SELECT * FROM feed WHERE fid = 0;
SELECT * FROM bundle WHERE bid = 0;
SELECT * FROM bundle ORDER BY title;
SELECT * FROM feed ORDER BY fid;
SELECT iid FROM item WHERE fid = 0 AND link = '%s';
SELECT iid FROM item WHERE fid = 0 AND title = '%s';
SELECT iid FROM item WHERE fid = 0 ORDER BY timestamp;
SELECT * FROM feed WHERE fid = 0;
SELECT * FROM bundle WHERE bid = 0;
SELECT f.*, COUNT(i.iid) AS items FROM feed f LEFT JOIN item i ON f.fid = i.fid GROUP BY f.fid, f.title, f.url, f.refresh, f.checked, f.attributes, f.link, f.description, f.etag, f.modified, f.image ORDER BY f.title;
SELECT * FROM bundle ORDER BY title;
SELECT i.*, f.title AS feed FROM item i INNER JOIN feed f ON i.fid = f.fid ORDER BY i.timestamp DESC, i.iid DESC;
SELECT i.*, f.title AS ftitle, f.link AS flink FROM item i INNER JOIN feed f ON i.fid = f.fid ORDER BY i.timestamp DESC, i.iid DESC;
SELECT * FROM feed WHERE fid = 0;
SELECT * FROM item WHERE fid = 0 ORDER BY timestamp DESC, iid DESC;
SELECT * FROM bundle WHERE bid = 0;
SELECT i.*, f.title AS ftitle, f.link AS flink FROM item i, feed f WHERE i.fid = f.fid ORDER BY timestamp DESC, iid DESC; -- (". implode(" OR ", $where) .") AND 
SELECT * FROM feed ORDER BY title;
SELECT * FROM feed ORDER BY title;
