SELECT ov.nid, ov.title, ov.teaser, ov.created, ov.name, ov.uid FROM ourView ov WHERE ov.type = 'blog' AND ov.uid = 0 AND ov.status = 1 ORDER BY ov.nid DESC;
SELECT ov.nid, ov.title, ov.teaser, ov.created, ov.name, ov.uid FROM ourView ov WHERE ov.type = 'blog' AND ov.status = 1 ORDER BY ov.nid DESC;
SELECT nid FROM node WHERE type = 'blog' AND uid = 0 AND status = 1 ORDER BY nid DESC;
SELECT nid FROM node WHERE type = 'blog' AND status = 1 ORDER BY nid DESC;
SELECT i.*, f.title as ftitle, f.link as flink FROM item i, feed f WHERE i.iid = 0 AND i.fid = f.fid;
SELECT n.title, n.nid FROM node n WHERE n.type = 'blog' AND n.status = 1 ORDER BY n.nid DESC;
