SELECT tid FROM term_data WHERE vid = 0;
SELECT * FROM vocabulary WHERE nodes = '%%%s%%' ORDER BY weight, name;
SELECT * FROM vocabulary ORDER BY weight, name;
SELECT * FROM vocabulary WHERE nodes = '%%%s%%' ORDER BY weight, name;
SELECT name FROM term_data WHERE tid = 0;
SELECT COUNT(n.nid) FROM node n WHERE n.nid = 0 AND ((n.body = '%%%s%%') OR (n.body = '%%%s%%'));
SELECT t.* FROM term_data t, term_node r WHERE t.tid = r.tid AND t.vid = 0 AND r.nid = 0 ORDER BY weight;
SELECT t.* FROM term_data t, term_node r WHERE r.tid = t.tid AND r.nid = 0 ORDER BY weight, name;
SELECT t.*, tid1, tid2 FROM term_relation , term_data t WHERE (t.tid = tid1 OR t.tid = tid2) AND (tid1 = 0 OR tid2 = 0) AND t.tid != 0 ORDER BY weight, name;
SELECT t.* FROM term_hierarchy h, term_data t WHERE h.parent = t.tid AND h.tid = 0 ORDER BY weight, name;
SELECT t.* FROM term_hierarchy h, term_data t WHERE t.vid = 0 AND h.tid = t.tid AND h.parent = 0 ORDER BY weight, name;
SELECT t.* FROM term_hierarchy h, term_data t WHERE h.tid = t.tid AND parent = 0 ORDER BY weight;
SELECT t.*, parent FROM term_data t, term_hierarchy h WHERE t.tid = h.tid AND t.vid = 0 ORDER BY weight, name;
SELECT name FROM term_synonym WHERE tid = 0;
SELECT * FROM term_synonym s, term_data t WHERE t.tid = s.tid AND s.name = '%s';
SELECT t.tid, COUNT(*) AS c FROM term_node t INNER JOIN node n ON t.nid = n.nid WHERE n.status = 1 GROUP BY t.tid;
SELECT t.tid, COUNT(*) AS c FROM term_node t, node n WHERE t.nid = n.nid AND n.status = 1 AND n.type = '%s' GROUP BY t.tid;
SELECT tid, parent FROM term_hierarchy ;
SELECT * FROM vocabulary WHERE LOWER('%s') = LOWER(name);
SELECT * FROM term_data WHERE LOWER('%s') = LOWER(name);
SELECT * FROM vocabulary WHERE vid = 0;
SELECT * FROM term_data WHERE tid = 0;
SELECT n.nid, n.title, n.type, n.created, n.changed, n.uid, n.static, n.created, u.name FROM node n INNER JOIN term_node r ON n.nid = r.nid INNER JOIN users u ON n.uid = u.uid WHERE r.tid IN (0,1) AND n.status = '1' ORDER BY static DESC, created DESC;
SELECT COUNT(n.nid) FROM node n INNER JOIN term_node r ON n.nid = r.nid INNER JOIN users u ON n.uid = u.uid WHERE r.tid IN (0,1) AND n.status = '1';
SELECT n.nid, n.title, n.type, n.created, n.changed, n.uid, u.name FROM node n INNER JOIN term_node r ON n.nid = r.nid INNER JOIN users u ON n.uid = u.uid WHERE r.tid IN (0,1) AND n.status = '1' GROUP BY n.nid, n.title, n.type, n.created, n.changed, n.uid, u.name ORDER BY static DESC, created DESC; -- HAVING COUNT(n.nid) = ". count($taxonomy->tids) ." 
SELECT n.nid FROM node n INNER JOIN term_node r ON n.nid = r.nid WHERE r.tid IN (0,1) AND n.status = '1' GROUP BY n.nid; -- HAVING COUNT(n.nid) = 
SELECT name FROM term_data WHERE tid IN (0,1);
