SELECT v.nid, v.title, v.teaser, v.created, v.name, v.uid FROM ourView v WHERE v.type = 'blog' AND v.uid = 0 AND v.status = 1 ORDER BY v.nid DESC;
SELECT v.nid, v.title, v.teaser, v.created, v.name, v.uid FROM ourView v WHERE v.type = 'blog' AND v.status = 1 ORDER BY v.nid DESC;
SELECT nid FROM node WHERE type = 'blog' AND uid = 0 AND status = 1 ORDER BY nid DESC;
SELECT nid FROM node WHERE type = 'blog' AND status = 1 ORDER BY nid DESC;
SELECT i.*, f.title as ftitle, f.link as flink FROM item i, feed f WHERE i.iid = 0 AND i.fid = f.fid;
SELECT n.title, n.nid FROM node n WHERE n.type = 'blog' AND n.status = 1 ORDER BY n.nid DESC;
