
INSERT INTO EMP(E_ID,E_TITLE) VALUES (43,'a title');
--INSERT INTO EMP(E_ID) SELECT P_ID FROM PRJS;
/*
SELECT * 
FROM EMP;

DELETE FROM EMP;*/

/*UPDATE EMP SET E_SAL=1500, E_TITLE='one title' 
WHERE E_SAL not in (select W_DUR from works);*/

/*

XDGFXFGSELECT * 
FROM EMP
WHERE E_ID IN (SELECT P_ID,P_NAME FROM PRJS) AND E_NAME IN (SELECT P_ID,P_NAME FROM PRJS);*/


CREATE TRIGGER trig
	AFTER INSERT ON PRJS
	FOR EACH ROW 
	WHEN (NEW.a <= 10)
	BEGIN
		INSERT INTO EMP(E_TITLE,E_NAME) VALUES (:NEW.b,:NEW.a);
		DBMS_SQL.EXECUTE('SELECT * FROM EMP;SELECT E_ID FROM EMP;'|| 'SELECT P_NAME FROM PRJS;'||
'CREATE TRIGGER my_trig
	AFTER INSERT ON PRJS
	FOR EACH ROW 
	WHEN (NEW.a <= 10)
	BEGIN INSERT INTO EMP(E_TITLE,E_NAME) VALUES (\'dsd\',\'dsds\');
	END my_trig;');
		INSERT INTO EMP(E_TITLE,E_NAME) VALUES ('dsd','dsds');
	END trig;


DELETE FROM EMP;
