CREATE PROCEDURE insertTuple(a INTEGER)
AS
BEGIN
	INSERT INTO EMP VALUES(12,'value2','value3',17);

	INSERT INTO EMP(E_ID) VALUES(12);

	INSERT INTO EMP(E_ID) SELECT P_ID FROM PRJS;

--	INSERT INTO EMP ((SELECT * FROM EMP));

END insertTuple;



CREATE PROCEDURE deleteTuple(a INTEGER)
AS
BEGIN
	DELETE FROM EMP 
	WHERE E_SAL=34;

	DELETE FROM WORKS;

	CURSOR my_cur IS
		SELECT * FROM EMP
		FOR UPDATE;

END deleteTuple;



CREATE FUNCTION updateTuple(a INTEGER) 
RETURN BOOLEAN IS
BEGIN

	ID	NUMBER(7);
  	SAL	NUMBER(7);

	SELECT E_ID,E_SAL
	INTO NMAX, NMIN
	FROM EMP
	WHERE E_SAL>1200;

	UPDATE EMP SET E_SAL=1500, E_ID=:a 
	WHERE E_SAL not in (select W_DUR from works);

	UPDATE EMP SET E_SAL=1500;

	RETURN TRUE;

END updateTuple;
