SELECT bid, title, info FROM {boxes} ORDER BY title;
SELECT * FROM {boxes} WHERE bid = %d;
SELECT * FROM {blocks} WHERE theme = '%s';
SELECT * FROM {boxes} WHERE bid = %d;
SELECT pages, visibility, custom FROM {blocks} WHERE module = '%s' AND delta = '%s';
SELECT info FROM {boxes} WHERE info = '%s';
SELECT * FROM {blocks} WHERE status = 1 AND custom != 0 ORDER BY weight, module, delta;
SELECT * FROM {blocks} WHERE theme = '%s' AND status = 1 ORDER BY region, weight, module;
