SELECT MAX(n.created) FROM {node} n INNER JOIN {poll} p ON p.nid = n.nid WHERE n.status = 1 AND p.active = 1 AND n.moderate = 0;
SELECT p.nid FROM {poll} p INNER JOIN {node} n ON p.nid = n.nid WHERE (n.created + p.runtime) < '. time() .' AND p.active = 1 AND p.runtime != 0;
SELECT runtime, active FROM {poll} WHERE nid = %d;
SELECT chtext, chvotes, chorder FROM {poll_choices} WHERE nid = %d ORDER BY chorder;
SELECT uid FROM {poll_votes} WHERE nid = %d AND uid = %d;
SELECT hostname FROM {poll_votes} WHERE nid = %d AND hostname = '%s';
SELECT n.nid, n.title, p.active, n.created, SUM(c.chvotes) AS votes FROM {node} n INNER JOIN {poll} p ON n.nid = p.nid INNER JOIN {poll_choices} c ON n.nid = c.nid WHERE n.status = 1 AND n.moderate = 0 GROUP BY n.nid, n.title, p.active, n.created ORDER BY n.created DESC;
