SELECT f.* FROM {files} f WHERE filepath = '%s';
SELECT SUM(filesize) FROM {files} f INNER JOIN {node} n ON f.nid = n.nid WHERE n.uid = %d;
SELECT SUM(filesize) FROM {files};
SELECT COUNT(fid) FROM {file_revisions} WHERE fid = %d;
SELECT * FROM {files} WHERE nid = %d;
SELECT COUNT(fid) FROM {file_revisions} WHERE fid = %d;
SELECT * FROM {files} f INNER JOIN {file_revisions} r ON f.fid = r.fid WHERE r.vid = %d ORDER BY f.fid;
