SELECT ov.nid, ov.title, ov.type, ov.changed, ov.uid, ov.name, l.last_comment_timestamp AS last_post, l.comment_count FROM ourView ov INNER JOIN node_comment_statistics l ON ov.nid = l.nid LEFT JOIN comments c ON ov.nid = c.nid AND (c.status = 0 OR c.status IS NULL) WHERE ov.status = 1 AND (ov.uid = 0 OR c.uid = 0) ORDER BY last_post DESC;
SELECT COUNT(n.nid) FROM node n LEFT JOIN comments c ON n.nid = c.nid AND (c.status = 0 OR c.status IS NULL) WHERE n.status = 1 AND (n.uid = 0 OR c.uid = 0);
SELECT ov.nid, ov.title, ov.type, ov.changed, ov.uid, ov.name, l.last_comment_timestamp AS last_post, l.comment_count FROM ourView ov INNER JOIN node_comment_statistics l ON ov.nid = l.nid WHERE ov.status = 1 ORDER BY last_post DESC;
SELECT COUNT(n.nid) FROM node n WHERE n.status = 1;
