SELECT bid, title, info FROM boxes ORDER BY title;
SELECT * FROM boxes WHERE bid = 0;
SELECT * FROM blocks;
SELECT * FROM blocks WHERE status > 0 AND region = 0 ORDER BY weight;
SELECT * FROM blocks WHERE status > 0 AND region = 1 ORDER BY weight;
SELECT * FROM blocks WHERE status > 0 ORDER BY weight;
SELECT * FROM boxes WHERE bid = 0;
SELECT * FROM blocks WHERE custom = 0 ORDER BY module, delta;
SELECT * FROM blocks WHERE custom = 0 ORDER BY module, delta;
