SELECT v.nid, v.title, v.teaser, v.created, v.name, v.uid FROM ourView v WHERE v.type = 'blog' AND v.uid = 0 AND v.status = 1 ORDER BY v.nid DESC ; -- LIMIT 15;
SELECT v.nid, v.title, v.teaser, v.created, v.name, v.uid FROM ourView v WHERE v.type = 'blog' AND v.status = 1 ORDER BY v.nid DESC ; -- LIMIT 15;
SELECT nid FROM node WHERE type = 'blog' AND uid = '$account->uid' AND status = 1 ORDER BY nid DESC;
SELECT nid FROM node WHERE type = 'blog' AND status = 1 ORDER BY nid DESC;
SELECT i.*, f.title as ftitle, f.link as flink FROM item i, feed f WHERE i.iid = 0 AND i.fid = f.fid;
SELECT v.uid, v.name, v.created, v.title, v.nid FROM ourView v WHERE v.type = 'blog' AND v.status = 1 ORDER BY v.nid DESC ; -- LIMIT 10;
