SELECT n.nid, n.title, n.type, n.changed, n.uid, u.name, MAX(n.changed), MAX(c.timestamp) AS last_activity FROM node n LEFT JOIN comments c ON n.nid = c.nid INNER JOIN users u ON n.uid = u.uid WHERE n.uid = 0 AND n.status = 1 GROUP BY n.nid, n.title, n.type, n.changed, n.uid, u.name;
SELECT COUNT(nid) FROM node WHERE status = 1 AND uid = 0;
SELECT n.nid, n.title, n.type, n.changed, n.uid, u.name, MAX(n.changed), MAX(c.timestamp) AS last_activity FROM node n LEFT JOIN comments c ON n.nid = c.nid INNER JOIN users u ON n.uid = u.uid WHERE n.status = 1 GROUP BY n.nid, n.title, n.type, n.changed, n.uid, u.name;
SELECT COUNT(nid) FROM node WHERE status = 1;
SELECT c.*, u.name FROM comments c INNER JOIN users u ON c.uid = u.uid WHERE c.uid = 0 AND c.nid = 0 AND c.status = 0 ORDER BY c.cid DESC;
SELECT c.*, u.name FROM comments c INNER JOIN users u ON c.uid = u.uid WHERE c.nid = 0 AND c.status = 0 ORDER BY c.cid DESC;
