SELECT uid, name, mail FROM users WHERE mail = '%s';
SELECT uid, name, mail FROM users WHERE name = '%s';
SELECT * FROM access WHERE status = '1' AND type = '%s';
SELECT uid FROM authmap WHERE authname = '%s';
SELECT u.uid, u.name, n.created, n.title, n.nid FROM node n LEFT JOIN users u ON n.uid = u.uid WHERE n.type = 'blog' AND n.status = 1 ORDER BY n.nid DESC; 
SELECT * FROM boxes WHERE bid = 0;
SELECT format, parent, weight, log FROM book WHERE nid = 0;
SELECT * FROM bundle WHERE bid = 0;
SELECT * FROM bundle WHERE bid = 0;
SELECT COUNT(c.nid) AS number FROM node n LEFT JOIN comments c ON n.nid = c.nid WHERE n.nid = 0 AND c.status = 0 GROUP BY n.nid;
SELECT c.*, u.uid, u.name, u.data FROM comments c LEFT JOIN users u ON c.uid = u.uid WHERE c.cid = 0 AND c.status = 0;
SELECT c.*, u.uid, u.name, u.data FROM comments c LEFT JOIN users u ON c.uid = u.uid WHERE c.cid = 0 AND c.status = 0;
SELECT c.*, u.uid, u.name, u.data FROM comments c LEFT JOIN users u ON c.uid = u.uid WHERE c.cid = 0 AND c.status != 2;
SELECT * FROM comments WHERE cid = 0;
SELECT comment FROM node WHERE nid = 0;
SELECT COUNT(c.nid) FROM node n LEFT JOIN comments c ON n.nid = c.nid WHERE n.nid = 0 AND n.status = 1 AND c.status = 0 AND timestamp > '$history' GROUP BY n.nid;
SELECT n.nid, n.title, u.uid, u.name FROM node n LEFT JOIN forum f ON n.nid = f.nid LEFT JOIN users u ON n.uid = u.uid WHERE n.type = 'forum' ORDER BY n.nid DESC; 
SELECT n.nid, n.title, u.uid, u.name, n.created, MAX(c.timestamp) AS sort FROM node n, forum f LEFT JOIN comments c ON c.nid = n.nid LEFT JOIN users u ON n.uid = u.uid WHERE n.type = 'forum' AND n.nid = f.nid AND f.shadow = 0 AND n.status = 1 GROUP BY n.nid ORDER BY sort DESC; 
SELECT c.*, u.name FROM comments c LEFT JOIN users u ON c.uid = u.uid WHERE c.timestamp > 0 AND c.nid = 0 AND c.status = 0 ORDER BY cid DESC;
SELECT c.*, u.name FROM comments c LEFT JOIN users u ON c.uid = u.uid WHERE c.timestamp > 0 AND c.uid = 0 AND c.nid = 0 AND c.status = 0 ORDER BY cid DESC;
SELECT data FROM users WHERE uid = 0;
SELECT COUNT(cid) FROM comments WHERE pid = 0 AND nid = 0 AND subject = '%s' AND comment = '%s';
SELECT iid FROM item WHERE fid = 0 AND link = '%s';
SELECT iid FROM item WHERE fid = 0 AND title = '%s';
SELECT * FROM feed WHERE fid = 0;
SELECT * FROM feed WHERE fid = 0;
SELECT filter, fid, minimum FROM moderation_filters WHERE fid = 0;
SELECT * FROM forum WHERE nid = 0 AND shadow = 0;
SELECT timestamp FROM history WHERE uid = 0 AND nid = 0;
SELECT timestamp FROM history WHERE uid = 0 AND nid = 0;
SELECT MAX(tid) AS high FROM term_data;
SELECT id FROM sequences WHERE name = '%s';
SELECT cid FROM cache WHERE cid = '%s';
SELECT nid FROM node WHERE status = 1 AND moderate = 0 AND (created > 'variable_getping_cron_last' OR changed > 'variable_getping_cron_last');
SELECT i.*, f.title as ftitle, f.link as flink FROM item i, feed f WHERE i.iid = 0 AND i.fid = f.fid;
SELECT * FROM feed WHERE url = '%s';
SELECT MAX(cid) FROM comments;
SELECT MAX(cid) FROM comments;
SELECT MAX(nid) FROM node;
SELECT MAX(tid) FROM term_data;
SELECT n.nid, n.title FROM node n LEFT JOIN book b ON n.nid = b.nid WHERE n.status = 1 AND b.parent = 0 AND (b.weight > 0 OR (b.weight = 0 AND n.title > '%s')) AND (n.moderate = 0 OR n.revisions != '') ORDER BY b.weight ASC, n.title ASC;
SELECT nid FROM comments WHERE cid = 0;
SELECT nid FROM node WHERE promote = '1' AND status = '1' ORDER BY created DESC; 
SELECT nid FROM node WHERE title = '%s' AND status = 1;
SELECT MAX(vid) AS high FROM vocabulary;
SELECT format, link, description FROM page WHERE nid = 0;
SELECT * FROM book WHERE nid = 0;
SELECT n.nid, n.title, b.parent FROM node n LEFT JOIN book b ON n.nid = b.nid WHERE n.nid = 0;
SELECT p.perm FROM role r, permission p WHERE r.rid = p.rid AND name = 'anonymous user';
SELECT p.perm FROM role r, permission p WHERE r.rid = p.rid AND name = '$user->role';
SELECT runtime, voters, active FROM poll WHERE nid = 0;
SELECT n.nid, n.title FROM node n LEFT JOIN book b ON n.nid = b.nid WHERE n.status = 1 AND b.parent = 0 AND (b.weight < 0 OR (b.weight = 0 AND n.title < '%s')) AND (n.moderate = 0 OR n.revisions != '') ORDER BY b.weight DESC, n.title DESC;
SELECT url, COUNT(url) AS cnt FROM accesslog WHERE nid = '$nid' AND url <> '' GROUP BY url ORDER BY cnt DESC;
SELECT url, COUNT(url) AS cnt FROM accesslog WHERE url <> '' GROUP BY url ORDER BY cnt DESC;
SELECT url,timestamp FROM accesslog WHERE nid='$nid' AND url <> '' ORDER BY timestamp DESC; 
SELECT url,timestamp FROM accesslog WHERE url <> '' ORDER BY timestamp DESC; 

-- SELECT n.nid, c.timestamp, u.name AS name, u.uid AS uid FROM term_node r, node n LEFT JOIN comments c ON n.nid = c.nid LEFT JOIN users u ON c.uid = u.uid WHERE r.tid = 0 AND n.nid = r.nid AND n.type = 'forum' AND n.status = 1 AND c.status = 0 ORDER BY c.timestamp DESC; 
SELECT ov.uid, ov.name, ov.created, ov.title, ov.nid FROM ourView ov WHERE ov.type = 'blog' AND ov.status = 1 ORDER BY ov.nid DESC; 

SELECT COUNT(c.cid) AS count_new, MIN(c.cid) AS id_first_new FROM node n LEFT JOIN comments c ON n.nid = c.nid WHERE n.nid = 0 AND timestamp > 0 AND c.status = 0;
SELECT nid FROM node WHERE type = 'blog' AND status = 1 ORDER BY nid DESC;
SELECT nid FROM node WHERE type = 'blog' AND uid = 0 AND status = 1 ORDER BY nid DESC;
SELECT nid, type FROM node WHERE promote = '1' AND status = '1' ORDER BY static DESC, created DESC;

-- SELECT n.*, u.name, u.uid FROM node n LEFT JOIN users u ON n.uid = u.uid;
SELECT ov.*, ov.name, ov.uid FROM ourView ov;

SELECT authname FROM authmap WHERE uid = 0 AND module = '$module';
SELECT authname, module FROM authmap WHERE authname = '%s';
SELECT bid, title, info FROM boxes ORDER BY title;
SELECT c.cid, c.pid, c.nid, c.subject, c.comment, c.timestamp, u.uid, u.name, u.data, c.score, c.users FROM comments c LEFT JOIN users u ON c.uid = u.uid WHERE c.cid = 0 AND c.status = 0 GROUP BY c.cid, c.pid, c.nid, c.subject, c.comment, c.timestamp, u.uid, u.name, u.data, c.score, c.users;
SELECT c.cid, c.subject, u.uid, u.name FROM comments c LEFT JOIN users u ON u.uid = c.uid WHERE nid = 0 AND c.status = 0 ORDER BY c.timestamp;
SELECT chtext, chvotes, chorder FROM poll_choices WHERE nid=0 ORDER BY chorder;
SELECT COUNT(cid) FROM comments WHERE pid = 0 AND status = 0;
SELECT COUNT(hostname) AS cnt, uid, MAX(timestamp) AS max_timestamp FROM accesslog WHERE timestamp >= '%s' GROUP BY uid ORDER BY max_timestamp DESC;
SELECT COUNT(*) from authmap WHERE uid != 0 AND authname = '%s';
SELECT COUNT(*) from authmap WHERE uid = 0 AND module = '$module[1]';
SELECT COUNT(nid) FROM node WHERE moderate = 1;
SELECT COUNT(timestamp) AS hits FROM accesslog WHERE timestamp >= '%s';
SELECT c.*, u.name, u.uid FROM comments c LEFT JOIN users u ON c.uid = u.uid WHERE c.cid = 0 AND c.status != 2;
SELECT c.*, u.name, u.uid FROM comments c LEFT JOIN users u ON u.uid = c.uid WHERE c.status = 0 ORDER BY timestamp DESC; 
SELECT f.*, COUNT(i.iid) AS items FROM feed f LEFT JOIN item i ON f.fid = i.fid GROUP BY f.fid, f.title, f.url, f.refresh, f.timestamp, f.attributes, f.link, f.description ORDER BY f.title;
SELECT fid, filter FROM moderation_filters;
SELECT fid, filter FROM moderation_filters;
SELECT fid, filter, minimum FROM moderation_filters ORDER BY minimum;
SELECT filename, type, status FROM system WHERE type = '%s';
SELECT * FROM access WHERE type = '%s' AND status = '0' ORDER BY mask;
SELECT * FROM access WHERE type = '%s' AND status = '1' ORDER BY mask;
SELECT * FROM blocks;
SELECT * FROM blocks WHERE custom = 0 ORDER BY module, delta;
SELECT * FROM blocks WHERE custom = 0 ORDER BY module, delta;
SELECT * FROM blocks WHERE status > 0 AND region = 0 ORDER BY weight;
SELECT * FROM blocks WHERE status > 0 AND region = 1 ORDER BY weight;
SELECT * FROM blocks WHERE status > 0 ORDER BY weight;
SELECT * FROM bundle ORDER BY title;
SELECT * FROM bundle ORDER BY title;
SELECT * FROM bundle ORDER BY title;
SELECT * FROM directory ORDER BY name;
SELECT * FROM feed;
SELECT * FROM feed ORDER BY fid;
SELECT * FROM feed ORDER BY fid;
SELECT * FROM feed ORDER BY title;
SELECT * FROM feed ORDER BY title;
SELECT * FROM feed WHERE timestamp + refresh < 'time()';
SELECT * FROM item WHERE fid = 0 ORDER BY iid DESC; 
SELECT * FROM item WHERE fid = 0 ORDER BY iid DESC; 
SELECT * FROM locales WHERE lid = 0;
SELECT * FROM role;
SELECT * FROM role ORDER BY name;
SELECT * FROM role ORDER BY name;
SELECT * FROM site ORDER BY name;
SELECT * FROM site WHERE timestamp = 0 OR timestamp + refresh <  'time()';
SELECT * FROM site WHERE timestamp > '(time() - 604800)' ORDER BY timestamp DESC; 
SELECT * FROM system where type = 'theme' AND status = '1' ORDER BY name;
SELECT * FROM users WHERE uid = 1;
SELECT * FROM variable;
SELECT * FROM vocabulary ORDER BY weight, name;
SELECT i.*, f.title AS feed FROM item i LEFT JOIN feed f ON i.fid = f.fid ORDER BY i.iid DESC; 
SELECT i.*, f.title AS ftitle, f.link AS flink FROM item i LEFT JOIN feed f ON i.fid = f.fid ORDER BY i.iid DESC; 
SELECT iid FROM item WHERE fid = 0 ORDER BY timestamp;
SELECT lid FROM locales WHERE string = '%s';
SELECT mid, value FROM moderation_roles WHERE rid = 0;
SELECT mid, vote FROM moderation_votes ORDER BY weight;
SELECT mid, vote, weight FROM moderation_votes ORDER BY weight;
SELECT name, filename FROM system WHERE type = 'module' AND status = '1' ORDER BY name;
SELECT name FROM term_synonym WHERE tid = 0;
SELECT nid,attributes FROM node WHERE attributes != '';
SELECT nid FROM node WHERE status = '1' AND created > '$date';
SELECT nid, timestamp FROM history WHERE uid = 0;
SELECT nid,type FROM node WHERE type = 'story' OR type = 'page' OR type = 'blog' OR type = 'forum' OR type = 'book';
SELECT nid, url, hostname, uid, MAX(timestamp) AS timestamp FROM accesslog WHERE uid <> '0' GROUP BY uid, nid, url, hostname ORDER BY timestamp DESC; 
SELECT nid, url, hostname, uid, timestamp FROM accesslog ORDER BY timestamp DESC; 
SELECT nid, url, hostname, uid, timestamp FROM accesslog WHERE hostname = '%s' ORDER BY timestamp DESC; 
SELECT nid, url, hostname, uid, timestamp FROM accesslog WHERE nid = 0 ORDER BY timestamp DESC; 
SELECT nid, url, hostname, uid, timestamp FROM accesslog WHERE uid = '%s' ORDER BY timestamp DESC; 
SELECT n.nid FROM node n LEFT JOIN book b ON n.nid = b.nid WHERE b.parent = 0 AND n.status = 1 AND (n.moderate = 0 OR n.revisions != '') ORDER BY b.weight, n.title;
SELECT n.nid FROM node n LEFT JOIN book b ON n.nid = b.nid WHERE b.parent = 0 ORDER BY b.weight, n.title;
SELECT n.nid FROM node n LEFT JOIN book b ON n.nid = b.nid WHERE n.status = 1 AND b.parent = '$parent' AND (n.moderate = 0 OR n.revisions != '');
SELECT n.nid FROM node n LEFT JOIN book b ON n.nid = b.nid WHERE n.status = 1 AND n.nid = 0 AND (n.moderate = 0 OR n.revisions != '') ORDER BY b.weight, n.title;
SELECT n.nid, n.title, b.parent FROM node n LEFT JOIN book b ON n.nid = b.nid WHERE n.status = '1' AND n.moderate = '0' ORDER BY b.weight, n.title;
SELECT n.nid, n.title, b.parent FROM node n LEFT JOIN book b ON n.nid = b.nid WHERE n.status = '1' ORDER BY b.weight, n.title;
SELECT n.nid, n.title, b.parent FROM node n LEFT JOIN book b ON n.nid = b.nid WHERE n.type = 'book';
SELECT n.nid, n.title FROM node n LEFT JOIN book b ON n.nid = b.nid WHERE b.parent = 0 ORDER BY b.weight, n.title;
SELECT n.nid, n.title FROM node n WHERE n.type = 'book' AND n.status = 0;
-- SELECT n.nid, n.title, n.teaser, n.created, u.name, u.uid FROM node n LEFT JOIN users u ON n.uid = u.uid WHERE n.type = 'blog' AND n.status = 1 ORDER BY n.nid DESC; 
SELECT ov.nid, ov.title, ov.teaser, ov.created, ov.name, ov.uid FROM ourView ov WHERE ov.type = 'blog' AND ov.status = 1 ORDER BY ov.nid DESC; 

-- SELECT n.nid, n.title, n.teaser, n.created, u.name, u.uid FROM node n LEFT JOIN users u ON n.uid = u.uid WHERE n.type = 'blog' AND u.uid = '$uid' AND n.status = 1 ORDER BY n.nid DESC; 
SELECT ov.nid, ov.title, ov.teaser, ov.created, ov.name, ov.uid FROM ourView ov WHERE ov.type = 'blog' AND ov.uid = '$uid' AND ov.status = 1 ORDER BY ov.nid DESC; 

SELECT n.nid, n.title, p.active, SUM(c.chvotes) AS votes FROM node n LEFT JOIN poll p ON n.nid=p.nid LEFT JOIN poll_choices c ON n.nid=c.nid WHERE type = 'poll' AND status = '1' AND moderate = '0' GROUP BY n.nid, n.title, p.active, n.created ORDER BY n.created DESC;
SELECT n.nid, n.title, p.link, p.description FROM page p LEFT JOIN node n ON p.nid = n.nid WHERE n.status = '1' AND p.link != '' ORDER BY p.link;

-- SELECT n.*, u.name FROM node n LEFT JOIN users u ON n.uid = u.uid WHERE n.uid = 0 ORDER BY n.nid DESC; 
SELECT ov.*, ov.name FROM ourView ov WHERE ov.uid = 0 ORDER BY ov.nid DESC; -- oeo? --
-- SELECT n.*, u.name, u.uid FROM node n LEFT JOIN users u ON n.uid = u.uid WHERE n.moderate = 1;
SELECT ov.*, ov.name, ov.uid FROM ourView ov WHERE ov.moderate = 1; -- oeo? --
-- SELECT n.*, u.name, u.uid FROM node n LEFT JOIN users u ON n.uid = u.uid WHERE n.title = '%s' AND n.status = 1 ORDER BY created DESC;
SELECT ov.*, ov.name, ov.uid FROM ourView ov WHERE ov.title = '%s' AND ov.status = 1 ORDER BY created DESC; -- oeo? --

SELECT p.nid FROM poll p LEFT JOIN node n ON p.nid=n.nid WHERE (n.created + p.runtime) < '". time() ."' AND p.active = '1' AND p.runtime != '0';
SELECT rid, mid, value FROM moderation_roles;
SELECT rid, name FROM role;
SELECT rid, name FROM role ORDER BY name;
SELECT r.nid FROM node n, history h, term_node r WHERE n.type = 'forum' AND n.status = 1 AND h.nid = n.nid AND r.nid = h.nid AND r.tid = 0 AND h.uid = 0;
SELECT r.rid, p.perm FROM role r LEFT JOIN permission p ON r.rid = p.rid WHERE tid = 0 ORDER BY name;
SELECT score FROM node WHERE nid = 0;
SELECT statistics.nid,node.title FROM statistics LEFT JOIN node ON statistics.nid = node.nid; 
SELECT string FROM locales;
SELECT t.* FROM term_data t, term_node r WHERE r.tid = t.tid AND r.nid = 0 ORDER BY weight, name;
SELECT t.* FROM term_data t, term_node r WHERE t.tid = r.tid AND t.vid = 0 AND r.nid = 0 ORDER BY weight;
SELECT t.* FROM term_hierarchy h, term_data t WHERE h.parent = t.tid AND h.tid = 0 ORDER BY weight, name;
SELECT t.* FROM term_hierarchy h, term_data t WHERE h.tid = t.tid AND parent = 0 ORDER BY weight;
SELECT t.* FROM term_hierarchy h, term_data t WHERE t.vid = 0 AND h.tid = t.tid AND h.parent = 0 ORDER BY weight, name;
SELECT tid, count(*) AS c FROM history h, term_node r, node n, forum f WHERE f.nid = r.nid AND r.nid = h.nid AND n.nid = h.nid AND f.shadow = 0 AND n.type = 'forum' AND n.status = 1 AND h.uid = 0 GROUP BY tid;
SELECT tid FROM term_data WHERE vid = 0;
SELECT tid, parent FROM term_hierarchy;
SELECT timestamp FROM history WHERE uid = 0 AND nid = 0;
SELECT t.*, parent FROM term_data t, term_hierarchy h WHERE t.tid = h.tid AND t.vid = 0 ORDER BY weight, name;
SELECT t.*, tid1, tid2 FROM term_relation, term_data t WHERE (t.tid = tid1 OR t.tid = tid2) AND (tid1 = 0 OR tid2 = 0) AND t.tid != 0 ORDER BY weight, name;
SELECT t.tid, COUNT(*) AS c FROM term_node t GROUP BY t.tid;
SELECT t.tid, COUNT(*) AS c FROM term_node t, node n WHERE t.nid = n.nid AND n.type = '%s' GROUP BY t.tid;
SELECT uid, name FROM users WHERE status != '0' ORDER BY uid DESC; 
SELECT u.*, r.name AS role FROM users u LEFT JOIN role r ON u.rid = r.rid WHERE u.status < 3; 
SELECT u.uid, u.name, u.timestamp, u.rid FROM users u LEFT JOIN role r ON u.rid = r.rid;
SELECT v.mid, v.vote, r.value FROM moderation_votes v, moderation_roles r WHERE v.mid = r.mid AND r.rid = 0 ORDER BY weight;
SELECT w.*, u.name, u.uid FROM watchdog w LEFT JOIN users u ON w.uid = u.uid;
SELECT w.*, u.name, u.uid FROM watchdog w LEFT JOIN users u ON w.uid = u.uid WHERE w.wid = 0;
SELECT c.cid as lno, c.subject as text1, c.comment as text2 FROM comments c WHERE c.status = 0 AND timestamp > 'variable_getcomment_cron_last';
SELECT * FROM boxes WHERE bid = 0;
SELECT * FROM bundle WHERE bid = 0;
SELECT * FROM feed WHERE fid = 0;
SELECT * FROM site WHERE sid = 0;
SELECT * FROM term_data WHERE tid = 0;
SELECT * FROM term_synonym s, term_data t WHERE t.tid = s.tid AND s.name = '%s';
SELECT * FROM vocabulary WHERE vid = 0;
SELECT statistics.nid, node.title, u.uid, u.name FROM statistics LEFT JOIN node ON statistics.nid = node.nid LEFT JOIN users u ON node.uid = u.uid WHERE node.status = 1; 
SELECT rid FROM role WHERE name = 'authenticated user';
SELECT * FROM role WHERE name = 'anonymous user';
SELECT * FROM role WHERE name = 'authenticated user';
SELECT * FROM role WHERE rid = 0;
SELECT n.nid as lno, n.title as text1, n.body as text2 FROM node n WHERE n.status = 1 AND moderate = 0 and (created > 'variable_getnode_cron_last' or changed > 'variable_getnode_cron_last');
SELECT n.nid, title, body, n.created, MAX(c.timestamp) AS date_sort, COUNT(c.nid) AS num_comments FROM node n, term_node t, forum f LEFT JOIN comments c ON c.nid = n.nid WHERE n.nid = t.nid AND n.nid = f.nid AND t.tid = 0 AND f.shadow = 0 AND n.status = 1 GROUP BY n.nid ORDER BY '$user->sortby';
SELECT n.nid, title, users.name AS name, users.uid AS uid, n.created AS timestamp, n.created, MAX(c.timestamp) AS date_sort, COUNT(c.nid) AS num_comments, icon, n.comment AS comment_mode, shadow FROM node n, term_node r LEFT JOIN users ON n.uid = users.uid LEFT JOIN comments c ON c.nid = n.nid LEFT JOIN forum f ON n.nid = f.nid WHERE n.nid = r.nid AND r.tid = 0 AND n.status = 1 AND n.type = 'forum' GROUP BY n.nid; 
SELECT n.nid, n.title, COUNT(n.nid) AS comments, MAX(c.timestamp) AS last_comment FROM comments c LEFT JOIN node n ON c.nid = n.nid WHERE c.status = 0 AND c.timestamp > '$period' AND c.uid = 0 GROUP BY n.nid, n.title ORDER BY last_comment DESC; 
SELECT n.nid, n.title, COUNT(n.nid) AS comments, MAX(c.timestamp) AS last_comment FROM comments c LEFT JOIN node n ON c.nid = n.nid WHERE c.status = 0 AND c.timestamp > '$period' GROUP BY n.nid, n.title ORDER BY last_comment DESC; 
SELECT totalcount, daycount, timestamp FROM statistics WHERE nid = 0;
SELECT name FROM term_data WHERE tid = 0;
SELECT minimum FROM moderation_filters WHERE fid = 0;
SELECT MAX(created) FROM node WHERE type = 'poll' AND status = '1' AND moderate = '0';
SELECT title FROM node WHERE nid = 0;
SELECT n.nid, n.created AS timestamp, u.name AS name, u.uid AS uid FROM node n, term_node r LEFT JOIN users u ON n.uid = u.uid WHERE r.tid = 0 AND n.nid = r.nid AND n.type = 'forum' AND n.status = 1 ORDER BY timestamp DESC; 
SELECT COUNT(*) AS cnt FROM comments c, term_node r, node n WHERE r.tid = 0 AND n.nid = r.nid AND n.nid = c.nid AND n.status = 1 AND c.status = 0 AND n.type = 'forum';
SELECT COUNT(cid) AS cnt FROM comments WHERE nid = 0 AND status = 0;
SELECT COUNT(n.nid) AS cnt FROM node n, term_node r, forum f WHERE r.tid = 0 AND n.nid = r.nid AND n.nid = f.nid AND n.status = 1 AND n.type = 'forum' AND f.shadow = 0;
SELECT c.timestamp, u.name, u.uid FROM comments c LEFT JOIN users u ON c.uid = u.uid WHERE c.nid = 0 AND c.status = 0 ORDER BY c.timestamp DESC; 
SELECT timestamp FROM comments WHERE nid = 0 AND status = 0 ORDER BY timestamp DESC; 
SELECT vote, weight FROM moderation_votes WHERE mid = 0;
SELECT weight FROM book WHERE nid = 0;
SELECT * FROM access WHERE status = '1' AND type = '%s' AND LOWER('%s') = LOWER(mask);
SELECT * FROM vocabulary WHERE types = '%%%s%%' ORDER BY weight, name;
SELECT * FROM term_data WHERE LOWER('%s') = LOWER(name);
SELECT * FROM vocabulary WHERE LOWER('%s') = LOWER(name);
SELECT * FROM access WHERE status = '0' AND type = '%s' AND LOWER('%s') = LOWER(mask);
SELECT mail FROM users WHERE LOWER(mail) = LOWER('%s');
SELECT mail FROM users WHERE LOWER(mail) = LOWER('%s');
SELECT name FROM users WHERE LOWER(name) = LOWER('%s');
SELECT name FROM users WHERE LOWER(name) = LOWER('%s');
SELECT uid FROM users WHERE uid != 0 AND LOWER(name) = LOWER('%s');
SELECT uid FROM users WHERE uid != '$user->uid' AND LOWER(name) = LOWER('%s');
SELECT uid FROM users WHERE uid != 0 AND LOWER(mail) = LOWER('%s');
SELECT uid FROM users WHERE uid != '$user->uid' AND LOWER(mail) = LOWER('%s');
SELECT * FROM blocks WHERE (status = '1' OR custom = '1') AND region = '%s' ;
SELECT c.cid as cid, c.pid, c.nid, c.subject, c.comment, c.timestamp, u.uid, u.name, u.data, c.score, c.users FROM comments c LEFT JOIN users u ON c.uid = u.uid WHERE c.nid = 'check_query($nid)' AND c.status = 0;
SELECT COUNT(n.nid) FROM node n WHERE n.nid = 0 AND ((n.body = '%%%s%%') OR (n.body = '%%%s%%'));
SELECT r.rid, r.name FROM role r, permission p WHERE r.rid = p.rid AND p.perm = '%moderate comments%';
SELECT r.rid, r.name FROM role r, permission p WHERE r.rid = p.rid AND p.perm = '%post comments%';
SELECT url, COUNT(url) AS cnt FROM accesslog WHERE nid = '$nid' AND url = '%check_input($HTTP_HOST)%' GROUP BY url ORDER BY cnt DESC;
SELECT url, COUNT(url) AS cnt FROM accesslog WHERE nid = '$nid' AND url <> '%check_input($HTTP_HOST)%' AND url <> '' GROUP BY url ORDER BY cnt DESC;
SELECT url, COUNT(url) AS cnt FROM accesslog WHERE url = '%check_input($HTTP_HOST)%' GROUP BY url ORDER BY cnt DESC;
SELECT url, COUNT(url) AS cnt FROM accesslog WHERE url <> '%check_input($HTTP_HOST)%' AND url <> '' GROUP BY url ORDER BY cnt DESC;
SELECT url,timestamp FROM accesslog WHERE nid='$nid' AND url = '%check_input($HTTP_HOST)%' ORDER BY timestamp DESC; 
SELECT url,timestamp FROM accesslog WHERE nid='$nid' AND url <> '%check_input($HTTP_HOST)%' AND url <> '' ORDER BY timestamp DESC; 
SELECT url,timestamp FROM accesslog WHERE url = '%check_input($HTTP_HOST)%' ORDER BY timestamp DESC; 
SELECT url,timestamp FROM accesslog WHERE url <> '%check_input($HTTP_HOST)%' AND url <> '' ORDER BY timestamp DESC; 
SELECT * FROM users WHERE name = '%$keys%'; 
SELECT * FROM variable WHERE value <> 's';
SELECT * FROM vocabulary WHERE types = '%%%s%%' ORDER BY weight, name;