SELECT uid, name, mail FROM users WHERE status = 1 AND LOWER(mail) = '%s';
SELECT uid, name, mail FROM users WHERE status = 1 AND LOWER(name) = '%s';
SELECT rid FROM role WHERE name = 'Authenticated user';
SELECT COUNT(dst) FROM url_alias WHERE dst = '%s';
SELECT * FROM access WHERE status = '1' AND type = '%s' AND LOWER('%s') = LOWER(mask);
SELECT COUNT(*) FROM forum f INNER JOIN node n ON f.nid = n.nid WHERE f.tid = 0 AND n.status = 1 AND n.created <= 0 AND f.shadow = 0;
SELECT n.title, n.nid FROM node n WHERE n.type = 'blog' AND n.status = 1 ORDER BY n.nid DESC;
SELECT * FROM boxes WHERE bid = 0;
SELECT format, parent, weight, log FROM book WHERE nid = 0;
SELECT * FROM book WHERE nid = 0;
SELECT * FROM bundle WHERE bid = 0;
SELECT * FROM bundle WHERE bid = 0;
SELECT MAX(bid) FROM bundle;
SELECT data, created, headers FROM cache WHERE cid = '%s';
SELECT COUNT(cid) FROM comments WHERE nid = 0 AND status = 0;
SELECT COUNT(cid) FROM comments WHERE pid = 0 AND status = 0;
SELECT * FROM vocabulary WHERE nodes = '%%%s%%' ORDER BY weight, name;
SELECT n.nid, n.title FROM node n INNER JOIN book b ON n.nid = b.nid WHERE b.parent = 0 AND n.status = 1 AND (n.moderate = 0 OR n.revisions != '') ORDER BY b.weight ASC, n.title ASC;
SELECT c.*, u.name, u.uid FROM comments c INNER JOIN users u ON u.uid = c.uid WHERE c.cid = 0;
SELECT c.*, u.uid, u.name, u.data FROM comments c INNER JOIN users u ON c.uid = u.uid WHERE c.cid = 0 AND c.status = 0;
SELECT c.*, u.uid, u.name, u.data FROM comments c INNER JOIN users u ON c.uid = u.uid WHERE c.cid = 0 AND c.status = 0;
SELECT c.*, u.uid, u.name, u.data FROM comments c INNER JOIN users u ON c.uid = u.uid WHERE c.cid = 0 AND c.status != 2;
SELECT * FROM comments WHERE cid = 0;
SELECT comment FROM node WHERE nid = 0;
SELECT nid, title FROM node WHERE type = 'forum' AND status = 1 ORDER BY nid DESC;
SELECT n.nid, n.title, n.created, MAX(c.timestamp) AS sort FROM node n LEFT JOIN comments c ON n.nid = c.nid WHERE n.type = 'forum' AND n.status = 1 GROUP BY n.nid, n.title, n.created ORDER BY sort DESC ;
SELECT c.*, u.name FROM comments c INNER JOIN users u ON c.uid = u.uid WHERE c.nid = 0 AND c.status = 0 ORDER BY c.cid DESC;
SELECT c.*, u.name FROM comments c INNER JOIN users u ON c.uid = u.uid WHERE c.uid = 0 AND c.nid = 0 AND c.status = 0 ORDER BY c.cid DESC;
SELECT data FROM users WHERE uid = 0;
SELECT * FROM term_data WHERE LOWER('%s') = LOWER(name);
SELECT * FROM vocabulary WHERE LOWER('%s') = LOWER(name);
SELECT * FROM access WHERE status = '0' AND type = '%s' AND LOWER('%s') = LOWER(mask);
SELECT n.nid, n.title FROM node n INNER JOIN book b ON n.nid = b.nid WHERE b.parent = 0 AND n.status = 1 AND (n.moderate = 0 OR n.revisions != '') AND (b.weight < 0 OR (b.weight = 0 AND n.title < '%s')) ORDER BY b.weight DESC, n.title DESC;
SELECT COUNT(cid) FROM comments WHERE pid = 0 AND nid = 0 AND subject = '%s' AND comment = '%s';
SELECT mail FROM users WHERE LOWER(mail) = LOWER('%s');
SELECT mail FROM users WHERE LOWER(mail) = LOWER('%s') OR LOWER(init) = LOWER('%s');
SELECT name FROM users WHERE LOWER(name) = LOWER('%s');
SELECT name FROM users WHERE LOWER(name) = LOWER('%s');
SELECT uid FROM users WHERE uid != 0 AND LOWER(name) = LOWER('%s');
SELECT uid FROM users WHERE uid != 0 AND LOWER(name) = LOWER('%s');
SELECT COUNT(dst) FROM url_alias WHERE dst = '%s' AND src != '%s';
SELECT uid FROM users WHERE uid != 0 AND LOWER(mail) = LOWER('%s');
SELECT uid FROM users WHERE uid != 0 AND LOWER(mail) = LOWER('%s');
SELECT iid FROM item WHERE fid = 0 AND link = '%s';
SELECT iid FROM item WHERE fid = 0 AND title = '%s';
SELECT * FROM feed WHERE fid = 0;
SELECT * FROM feed WHERE fid = 0;
SELECT MAX(fid) FROM feed;
SELECT filter, fid, minimum FROM moderation_filters WHERE fid = 0;
SELECT * FROM forum WHERE nid = 0;
SELECT COUNT( sid) AS cnt FROM sessions WHERE timestamp >= 0 AND uid = 0;
SELECT timestamp FROM history WHERE uid = 0 AND nid = 0;
SELECT timestamp FROM history WHERE uid = 0 AND nid = 0;
SELECT id FROM sequences WHERE name = '%s';
SELECT nid FROM node WHERE status = 1 AND moderate = 0 AND (created > 'variable_get(ping_cron_last, time())' OR changed > 'variable_get("ping_cron_last, time())');
SELECT COUNT(dst) FROM url_alias WHERE pid != '%d' AND dst = '%s';
SELECT COUNT(*) FROM term_data WHERE tid = 0 AND vid = 0;
SELECT COUNT(src) FROM url_alias WHERE pid != '%d' AND src = '%s';
SELECT i.*, f.title as ftitle, f.link as flink FROM item i, feed f WHERE i.iid = 0 AND i.fid = f.fid;
SELECT MAX(cid) FROM comments;
SELECT MAX(cid) FROM comments;
SELECT MAX(nid) FROM node;
SELECT MAX(tid) FROM term_data;
SELECT MAX(vid) FROM vocabulary;
SELECT n.nid, n.title, b.parent FROM node n INNER JOIN book b ON n.nid = b.nid WHERE b.parent = 0 ORDER BY b.weight DESC, n.title DESC;
SELECT MAX(aid) FROM access;
SELECT MAX(thread) FROM comments WHERE nid = 0;
SELECT MAX(thread) FROM comments WHERE thread = '%s.%%' AND nid = 0;
SELECT n.nid, n.title FROM node n INNER JOIN book b ON n.nid = b.nid WHERE b.parent = 0 AND n.status = 1 AND (n.moderate = 0 OR n.revisions != '') AND (b.weight > 0 OR (b.weight = 0 AND n.title > '%s')) ORDER BY b.weight ASC, n.title ASC;
SELECT body FROM node WHERE nid = 0;
SELECT nid FROM comments WHERE cid = 0;
SELECT nid FROM node WHERE promote = 1 AND status = 1 ORDER BY created DESC;
SELECT * FROM book WHERE nid = 0;
SELECT n.nid, n.title, b.parent FROM node n INNER JOIN book b ON n.nid = b.nid WHERE n.nid = 0;
SELECT * FROM comments WHERE cid = 0;
SELECT n.nid, n.title, b.parent FROM node n INNER JOIN book b ON n.nid = b.nid WHERE n.nid = 0;
SELECT COUNT(src) FROM url_alias WHERE src = '%s';
SELECT p.perm FROM role r, permission p WHERE r.rid = p.rid AND r.rid = 0;
SELECT runtime, voters, active FROM poll WHERE nid = 0;
SELECT n.nid, n.title FROM node n INNER JOIN book b ON n.nid = b.nid WHERE n.nid = 0 AND n.status = 1 AND (n.moderate = 0 OR n.revisions != '');
SELECT COUNT((url)) FROM accesslog WHERE url <> '';
SELECT COUNT((url)) FROM accesslog WHERE url <> '' AND url = '% check_query($_SERVER[HTTP_HOST]) %';
SELECT COUNT((url)) FROM accesslog WHERE url <> '' AND url <> '% check_query($_SERVER[HTTP_HOST]) %';
SELECT c.cid as cid, c.pid, c.nid, c.subject, c.comment, c.timestamp, u.uid, u.name, u.data, c.score, c.users, c.thread FROM comments c INNER JOIN users u ON c.uid = u.uid WHERE c.nid = 0 AND c.status = 0;
SELECT url, MAX(timestamp) AS last_view, COUNT(url) AS cnt FROM accesslog WHERE url <> '' GROUP BY url;
SELECT url, MAX(timestamp) AS last_view, COUNT(url) AS cnt FROM accesslog WHERE url = '% check_query($_SERVER[HTTP_HOST]) %' GROUP BY url;
SELECT url, MAX(timestamp) AS last_view, COUNT(url) AS cnt FROM accesslog WHERE url <> '% check_query($_SERVER[HTTP_HOST]) %' AND url <> '' GROUP BY url;
SELECT COUNT(timestamp) AS hits FROM accesslog WHERE timestamp >= 0;
SELECT COUNT(timestamp) AS hits FROM accesslog WHERE timestamp >= 0;
SELECT COUNT(*) FROM forum f INNER JOIN node n ON f.nid = n.nid INNER JOIN history h ON n.nid = h.nid WHERE n.status = 1 AND f.tid = 0 AND h.uid = 0 AND n.created > 0 AND f.shadow = 0;
SELECT n.nid, c.timestamp, u.name AS name, u.uid AS uid FROM forum f INNER JOIN node n ON n.nid = f.nid INNER JOIN comments c ON n.nid = c.nid INNER JOIN users u ON c.uid = u.uid WHERE f.tid = 0 AND n.nid = f.nid AND n.type = 'forum' AND n.status = 1 AND c.status = 0 ORDER BY c.timestamp DESC;
SELECT cid, pid FROM comments where nid = 0 ORDER BY timestamp;
SELECT n.nid, t.tid FROM node n, term_node t WHERE n.nid = t.nid AND type = 'forum';
SELECT * FROM item WHERE fid = 0 ORDER BY timestamp DESC, iid DESC;
SELECT * FROM item WHERE fid = 0 ORDER BY timestamp DESC, iid DESC;
SELECT * FROM users WHERE LOWER(name) = '%%%s%%';
SELECT i.*, f.title AS feed FROM item i INNER JOIN feed f ON i.fid = f.fid ORDER BY i.timestamp DESC, i.iid DESC;
SELECT i.*, f.title AS ftitle, f.link AS flink FROM item i INNER JOIN feed f ON i.fid = f.fid ORDER BY i.timestamp DESC, i.iid DESC;
SELECT nid FROM node WHERE status = '1' AND created > 0 AND created < 0 ORDER BY created;
SELECT n.nid, n.title FROM node_counter s INNER JOIN node n ON s.nid = n.nid 
SELECT n.nid, n.title, n.body, n.created, u.name FROM node n, users u WHERE n.uid=u.uid AND n.type = 'blog' AND n.uid = 0 ORDER BY n.created DESC;

-- SELECT n.nid, n.title, n.teaser, n.created, u.name, u.uid FROM node n INNER JOIN users u ON n.uid = u.uid WHERE n.type = 'blog' AND n.status = 1 ORDER BY n.nid DESC;
SELECT ov.nid, ov.title, ov.teaser, ov.created, ov.name, ov.uid FROM ourViewN ov WHERE ov.type = 'blog' AND ov.status = 1 ORDER BY ov.nid DESC;

-- SELECT n.nid, n.title, n.teaser, n.created, u.name, u.uid FROM node n INNER JOIN users u ON n.uid = u.uid WHERE n.type = 'blog' AND u.uid = 0 AND n.status = 1 ORDER BY n.nid DESC;
SELECT ov.nid, ov.title, ov.teaser, ov.created, ov.name, ov.uid FROM ourViewN ov WHERE ov.type = 'blog' AND ov.uid = 0 AND ov.status = 1 ORDER BY ov.nid DESC;

SELECT uid, name FROM users WHERE status != '0' ORDER BY uid DESC;
SELECT u.*, r.name AS role FROM role r INNER JOIN users u ON r.rid = u.rid WHERE u.status < 3;
SELECT u.*, s.*, r.name AS role FROM users u INNER JOIN sessions s ON u.uid = s.uid LEFT JOIN role r ON u.rid = r.rid WHERE s.sid = '%s' AND u.status < 3;
SELECT authname FROM authmap WHERE uid = 0 AND module = '%s';
SELECT authname, module FROM authmap WHERE authname = '%s';
SELECT bid, title, info FROM boxes ORDER BY title;
SELECT c.cid, c.pid, c.nid, c.subject, c.comment, c.timestamp, u.uid, u.name, u.data, c.score, c.users FROM comments c INNER JOIN users u ON c.uid = u.uid WHERE c.cid = 0 AND c.status = 0 GROUP BY c.cid, c.pid, c.nid, c.subject, c.comment, c.timestamp, u.uid, u.name, u.data, c.score, c.users;
SELECT c.cid, c.subject, u.uid, u.name FROM comments c INNER JOIN users u ON u.uid = c.uid WHERE nid = 0 AND c.status = 0 ORDER BY c.timestamp;
SELECT chtext, chvotes, chorder FROM poll_choices WHERE nid=0 ORDER BY chorder;
SELECT cid, subject FROM comments WHERE pid = 0;
SELECT COUNT(*) from authmap WHERE uid != 0 AND authname = '%s';
SELECT COUNT(nid) FROM node WHERE moderate = 1;
SELECT created FROM node WHERE status = 1 AND created > '$start_of_month' AND created < '$end_of_month';
SELECT c.*, u.name, u.uid FROM comments c INNER JOIN users u ON c.uid = u.uid WHERE c.cid = 0 AND c.status != 2;
SELECT (nid) FROM comments WHERE thread = '';
SELECT (type) FROM watchdog;
SELECT f.*, COUNT(i.iid) AS items FROM feed f LEFT JOIN item i ON f.fid = i.fid GROUP BY f.fid, f.title, f.url, f.refresh, f.checked, f.attributes, f.link, f.description, f.etag, f.modified, f.image ORDER BY f.title;
SELECT fid, filter FROM moderation_filters ;
SELECT fid, filter FROM moderation_filters ;
SELECT fid, filter, minimum FROM moderation_filters ORDER BY minimum;
SELECT filename, type, status, throttle FROM system WHERE type = '%s';
SELECT * FROM access WHERE type = '%s' AND status = '0' ORDER BY mask;
SELECT * FROM access WHERE type = '%s' AND status = '1' ORDER BY mask;
SELECT * FROM blocks ;
SELECT * FROM blocks WHERE custom = 0 ORDER BY module, delta;
SELECT * FROM blocks WHERE status > 0 AND region = 0 ORDER BY weight;
SELECT * FROM blocks WHERE status > 0 AND region = 1 ORDER BY weight;
SELECT * FROM blocks WHERE status > 0 ORDER BY weight;
SELECT * FROM blocks WHERE (status = '1' OR custom = '1');
SELECT * FROM bundle ORDER BY title;
SELECT * FROM bundle ORDER BY title;
SELECT * FROM bundle ORDER BY title;
SELECT * FROM directory ORDER BY name;
SELECT * FROM feed;
SELECT * FROM feed ORDER BY fid;
SELECT * FROM feed ORDER BY fid;
SELECT * FROM feed ORDER BY title;
SELECT * FROM feed ORDER BY title;
SELECT * FROM feed WHERE checked + refresh < 0;
SELECT * FROM filters ORDER BY weight ASC;
SELECT * FROM locales WHERE lid = 0;
SELECT * FROM role ;
SELECT * FROM role ORDER BY name;
SELECT * FROM role ORDER BY name;
SELECT * FROM system where type = 'theme' AND status = '1' ORDER BY name;
SELECT * FROM url_alias;
SELECT * FROM users WHERE uid = 1;
SELECT * FROM variable ;
SELECT * FROM variable WHERE value <> 's';
SELECT * FROM vocabulary ORDER BY weight, name;
SELECT * FROM vocabulary WHERE nodes = '%%%s%%' ORDER BY weight, name;
SELECT iid FROM item WHERE fid = 0 ORDER BY timestamp;
SELECT lid FROM locales WHERE string = '%s';
SELECT mid, value FROM moderation_roles WHERE rid = 0;
SELECT mid, vote FROM moderation_votes ORDER BY weight;
SELECT mid, vote, weight FROM moderation_votes ORDER BY weight;
SELECT name, filename, throttle, bootstrap FROM system WHERE type = 'module' AND status = 1;
SELECT name, filename, throttle, bootstrap FROM system WHERE type = 'module' AND status = 1 AND bootstrap = 1;
SELECT name FROM term_synonym WHERE tid = 0;
SELECT nid, timestamp FROM history WHERE uid = 0;
SELECT n.nid FROM node n, history h, forum f WHERE n.type = 'forum' AND n.status = 1 AND h.nid = n.nid AND f.nid = h.nid AND f.tid = 0 AND h.uid = 0;
SELECT n.nid FROM node n INNER JOIN book b ON n.nid = b.nid WHERE b.parent = 0 AND n.status = 1 AND (n.moderate = 0 OR n.revisions IS NOT NULL) ORDER BY b.weight, n.title;
SELECT n.nid FROM node n INNER JOIN book b ON n.nid = b.nid WHERE b.parent = 0 ORDER BY b.weight, n.title;
SELECT n.nid FROM node n INNER JOIN book b ON n.nid = b.nid WHERE n.status = 1 AND b.parent = '$parent' AND (n.moderate = 0 OR n.revisions IS NOT NULL) ORDER BY b.weight, n.title;
SELECT n.nid FROM node n INNER JOIN book b ON n.nid = b.nid WHERE n.status = 1 AND n.nid = 0 AND (n.moderate = 0 OR n.revisions IS NOT NULL) ORDER BY b.weight, n.title;
SELECT n.nid, n.title, b.parent FROM node n INNER JOIN book b ON n.nid = b.nid WHERE n.status = '1' AND n.moderate = '0' ORDER BY b.weight, n.title;
SELECT n.nid, n.title, b.parent FROM node n INNER JOIN book b ON n.nid = b.nid WHERE n.status = '1' ORDER BY b.weight, n.title;
SELECT n.nid, n.title FROM node n INNER JOIN book b ON n.nid = b.nid WHERE b.parent = 0 ORDER BY b.weight, n.title;
SELECT n.nid, n.title, n.created, MAX(c.timestamp) AS date_sort, COUNT(c.nid) AS num_comments FROM node n INNER JOIN forum f ON n.nid = f.nid INNER JOIN comments c ON n.nid = c.nid WHERE n.nid = f.nid AND f.tid = 0 AND n.status = 1 GROUP BY n.nid, n.title, n.created 
SELECT n.nid, n.title, n.status, b.parent FROM node n INNER JOIN book b ON n.nid = b.nid;
SELECT n.nid, n.title, p.link, p.description FROM page p INNER JOIN node n ON p.nid = n.nid WHERE n.status = '1' AND p.link != '' ORDER BY p.link;

-- SELECT n.*, u.name, u.uid FROM node n INNER JOIN users u ON n.uid = u.uid WHERE n.title = '%%%s%%' AND n.status = 1 ORDER BY n.created DESC;
SELECT ov.*, ov.name, ov.uid FROM ourViewN ov WHERE ov.title = '%%%s%%' AND ov.status = 1 ORDER BY ov.created DESC;

-- SELECT n.*, u.name, u.uid FROM node n INNER JOIN users u ON n.uid = u.uid WHERE n.title = '%s' AND n.status = 1 ORDER BY n.created DESC;
SELECT ov.*, ov.name, ov.uid FROM ourViewN ov WHERE ov.title = '%s' AND ov.status = 1 ORDER BY ov.created DESC;

SELECT p.nid FROM poll p INNER JOIN node n ON p.nid=n.nid WHERE (n.created + p.runtime) < 'time()' AND p.active = '1' AND p.runtime != '0';
SELECT rid, mid, value FROM moderation_roles ;
SELECT rid, name FROM role ORDER BY name;
SELECT r.rid, p.perm FROM role r LEFT JOIN permission p ON r.rid = p.rid ORDER BY name;
SELECT r.rid, r.name FROM role r, permission p WHERE r.rid = p.rid AND p.perm = '%moderate comments%';
SELECT r.rid, r.name FROM role r, permission p WHERE r.rid = p.rid AND p.perm = '%post comments%';
SELECT score FROM node WHERE nid = 0;
SELECT string FROM locales WHERE LENGTH(string) < 75;
SELECT t.* FROM term_data t, term_node r WHERE r.tid = t.tid AND r.nid = 0 ORDER BY weight, name;
SELECT t.* FROM term_data t, term_node r WHERE t.tid = r.tid AND t.vid = 0 AND r.nid = 0 ORDER BY weight;
SELECT t.* FROM term_hierarchy h, term_data t WHERE h.parent = t.tid AND h.tid = 0 ORDER BY weight, name;
SELECT t.* FROM term_hierarchy h, term_data t WHERE h.tid = t.tid AND parent = 0 ORDER BY weight;
SELECT t.* FROM term_hierarchy h, term_data t WHERE t.vid = 0 AND h.tid = t.tid AND h.parent = 0 ORDER BY weight, name;
SELECT tid FROM term_data WHERE vid = 0;
SELECT tid, parent FROM term_hierarchy ;
SELECT timestamp FROM history WHERE uid = 0 AND nid = 0;
SELECT t.*, parent FROM term_data t, term_hierarchy h WHERE t.tid = h.tid AND t.vid = 0 ORDER BY weight, name;
SELECT t.*, tid1, tid2 FROM term_relation , term_data t WHERE (t.tid = tid1 OR t.tid = tid2) AND (tid1 = 0 OR tid2 = 0) AND t.tid != 0 ORDER BY weight, name;
SELECT t.tid, COUNT(*) AS c FROM term_node t INNER JOIN node n ON t.nid = n.nid WHERE n.status = 1 GROUP BY t.tid;
SELECT t.tid, COUNT(*) AS c FROM term_node t, node n WHERE t.nid = n.nid AND n.status = 1 AND n.type = '%s' GROUP BY t.tid;
SELECT uid FROM authmap WHERE authname = '%s';
SELECT u.*, r.name AS role FROM users u INNER JOIN role r ON u.rid = r.rid WHERE u.uid = 0;
SELECT v.mid, v.vote, r.value FROM moderation_votes v, moderation_roles r WHERE v.mid = r.mid AND r.rid = 0 ORDER BY weight;
SELECT w.*, u.name, u.uid FROM watchdog w INNER JOIN users u ON w.uid = u.uid WHERE w.wid = 0;
SELECT COUNT(c.cid) FROM node n INNER JOIN comments c ON n.nid = c.nid WHERE n.nid = 0 AND timestamp > 0 AND c.status = 0;
SELECT COUNT(*) FROM comments WHERE nid = 'check_query($nid)';
SELECT nid FROM node WHERE type = 'blog' AND status = 1 ORDER BY nid DESC;
SELECT nid FROM node WHERE type = 'blog' AND uid = '$account->uid' AND status = 1 ORDER BY nid DESC;
SELECT nid, type FROM node WHERE promote = 1 AND status = 1 ORDER BY static DESC, created DESC;
SELECT n.nid, n.title, p.active, SUM(c.chvotes) AS votes FROM node n INNER JOIN poll p ON n.nid=p.nid INNER JOIN poll_choices c ON n.nid=c.nid WHERE type = 'poll' AND status = '1' AND moderate = '0' GROUP BY n.nid, n.title, p.active, n.created ORDER BY n.created DESC;

-- SELECT n.*, u.name, u.uid FROM node n INNER JOIN users u ON n.uid = u.uid;
SELECT ov.*, ov.name, ov.uid FROM ourViewN ov;

SELECT c.cid as lno, c.subject as text1, c.comment as text2 FROM comments c WHERE c.status = 0 AND timestamp > 'variable_get(comment_cron_last, 1)';
SELECT * FROM boxes WHERE bid = 0;
SELECT * FROM bundle WHERE bid = 0;
SELECT * FROM feed WHERE fid = 0;
SELECT * FROM url_alias WHERE pid = 0;
SELECT format, link, description FROM page WHERE nid = 0;
SELECT * FROM term_data WHERE tid = 0;
SELECT * FROM term_synonym s, term_data t WHERE t.tid = s.tid AND s.name = '%s';
SELECT * FROM vocabulary WHERE vid = 0;
SELECT s.nid, n.title, u.uid, u.name FROM node_counter s INNER JOIN node n ON s.nid = n.nid INNER JOIN users u ON n.uid = u.uid AND n.status = 1 
SELECT COUNT(*) AS cnt FROM comments c INNER JOIN node n ON n.nid = c.nid INNER JOIN forum f ON n.nid = f.nid WHERE f.tid = 0 AND n.nid = f.nid AND n.nid = c.nid AND n.status = 1 AND c.status = 0 AND n.type = 'forum';
SELECT COUNT(*) FROM forum f INNER JOIN node n ON n.nid = f.nid WHERE f.tid = 0 AND n.status = 1 AND f.shadow = 0;
SELECT COUNT(n.nid) FROM node n WHERE n.nid = 0 AND ((n.body = '%%%s%%') OR (n.body = '%%%s%%'));
SELECT rid FROM role WHERE name = 'authenticated user';
SELECT * FROM role WHERE rid = 0;
SELECT n.nid as lno, n.title as text1, n.body as text2 FROM node n WHERE n.status = 1 AND moderate = 0 and (created > 'node_cron_last' or changed > 'node_cron_last');
SELECT COUNT((n.nid)) FROM node n INNER JOIN forum f ON n.nid = f.nid INNER JOIN term_node r ON n.nid = r.nid WHERE n.nid = r.nid AND ( (r.tid = 0 AND f.shadow = 1) OR f.tid = 0) AND n.status = 1 AND n.type = 'forum';
SELECT COUNT((n.nid)) FROM node n INNER JOIN term_node r ON n.nid = r.nid INNER JOIN users u ON n.uid = u.uid WHERE r.tid IN (0,1) AND n.status = '1';
SELECT a.nid, a.url, a.hostname, a.uid, a.timestamp, n.title FROM accesslog a INNER JOIN node n ON a.nid = n.nid WHERE a.nid = 0;
SELECT a.nid, a.url, a.hostname, a.uid, a.timestamp, n.title FROM accesslog a LEFT JOIN node n ON a.nid = n.nid;
SELECT a.nid, a.url, a.hostname, a.uid, a.timestamp, n.title FROM accesslog a LEFT JOIN node n ON a.nid = n.nid WHERE a.hostname = 0;
SELECT a.nid, a.url, a.hostname, a.uid, a.timestamp, n.title FROM accesslog a LEFT JOIN node n ON a.nid = n.nid WHERE a.uid = 0;
SELECT a.nid, a.url, a.hostname, a.uid, MAX(a.timestamp) AS timestamp, n.title FROM accesslog a LEFT JOIN node n ON a.nid = n.nid WHERE a.uid <> '0' GROUP BY a.uid, a.nid, a.url, a.hostname;
SELECT c.*, u.name, u.uid FROM comments c INNER JOIN users u ON u.uid = c.uid WHERE c.status = 'check_query($status)';
SELECT (n.nid), n.title, n.type, n.created, n.changed, n.uid, n.static, n.created, u.name FROM node n INNER JOIN term_node r ON n.nid = r.nid INNER JOIN users u ON n.uid = u.uid WHERE r.tid IN (0,1) AND n.status = '1' ORDER BY static DESC, created DESC;
SELECT * FROM url_alias;
SELECT name FROM term_data WHERE tid IN (0,1);
SELECT n.nid, n.title, n.type, n.changed, n.uid, u.name, MAX(n.changed, c.timestamp) AS last_activity FROM node n LEFT JOIN comments c ON n.nid = c.nid INNER JOIN users u ON n.uid = u.uid WHERE n.status = 1 GROUP BY n.nid, n.title, n.type, n.changed, n.uid, u.name;
SELECT n.nid, n.title, n.type, n.changed, n.uid, u.name, MAX(n.changed, c.timestamp) AS last_activity FROM node n LEFT JOIN comments c ON n.nid = c.nid INNER JOIN users u ON n.uid = u.uid WHERE n.uid = 0 AND n.status = 1 GROUP BY n.nid, n.title, n.type, n.changed, n.uid, u.name;
SELECT n.nid, n.title, u.name AS name, u.uid AS uid, n.created AS timestamp, n.created, MAX(c.timestamp) AS date_sort, COUNT(c.nid) AS num_comments, n.comment AS comment_mode, f.tid FROM node n INNER JOIN term_node r ON n.nid = r.nid INNER JOIN users u ON n.uid = u.uid LEFT JOIN comments c ON n.nid = c.nid INNER JOIN forum f ON n.nid = f.nid WHERE n.nid = r.nid AND ((r.tid = 0 AND f.shadow = 1) OR f.tid = 0) AND n.status = 1 AND n.type = 'forum' GROUP BY n.nid, n.title, u.name, u.uid, n.created, n.comment, f.tid;
SELECT s.nid, s.daycount, s.totalcount, s.timestamp, n.title FROM node_counter s INNER JOIN node n ON s.nid = n.nid;
SELECT u.uid, u.name, u.status, u.timestamp, r.name AS rolename FROM role r INNER JOIN users u ON r.rid = u.rid WHERE uid != 0;
SELECT w.*, u.name, u.uid FROM watchdog w INNER JOIN users u ON w.uid = u.uid;

-- SELECT n.*, u.name, u.uid FROM node n INNER JOIN users u ON n.uid = u.uid WHERE n.moderate = 1;
SELECT ov.*, ov.name, ov.uid FROM ourViewN ov WHERE ov.moderate = 1;

SELECT COUNT(nid) FROM node WHERE status = 1;
SELECT COUNT(nid) FROM node WHERE status = 1 AND uid = 0;
SELECT totalcount, daycount, timestamp FROM node_counter WHERE nid = 0;
SELECT name FROM term_data WHERE tid = 0;
SELECT minimum FROM moderation_filters WHERE fid = 0;
SELECT MAX(created) FROM node WHERE type = 'poll' AND status = '1' AND moderate = '0';
SELECT title FROM node WHERE nid = 0;
SELECT n.nid, n.created AS timestamp, u.name AS name, u.uid AS uid FROM forum f INNER JOIN node n ON n.nid = f.nid INNER JOIN users u ON n.uid = u.uid WHERE f.tid = 0 AND n.nid = f.nid AND n.type = 'forum' AND n.status = 1 ORDER BY timestamp DESC;
SELECT COUNT(c.nid) FROM node n INNER JOIN comments c ON n.nid = c.nid WHERE n.nid = 0 AND n.status = 1 AND c.status = 0 AND c.timestamp > 0;
SELECT  uid, MAX(timestamp) AS max_timestamp FROM sessions WHERE timestamp >= 0 AND uid != 0 GROUP BY uid ORDER BY max_timestamp DESC;
SELECT MAX(uid) FROM users;
SELECT c.timestamp, u.name, u.uid FROM comments c INNER JOIN users u ON c.uid = u.uid WHERE c.nid = 0 AND c.status = 0 ORDER BY c.timestamp DESC;
SELECT timestamp FROM comments WHERE nid = 0 AND status = 0 ORDER BY timestamp DESC;
SELECT COUNT(cid) AS cnt FROM comments WHERE nid = 0 AND status = 0;
SELECT vote, weight FROM moderation_votes WHERE mid = 0;
SELECT weight FROM book WHERE nid = 0;