SELECT i.*, f.title AS ftitle, f.link AS flink FROM aggregator_category_item c LEFT JOIN aggregator_item i ON c.iid = i.iid LEFT JOIN aggregator_feed f ON i.fid = f.fid WHERE cid = '. $category->cid .' ORDER BY timestamp DESC, iid DESC;
SELECT i.*, f.title AS ftitle, f.link AS flink FROM aggregator_item i INNER JOIN aggregator_feed f ON i.fid = f.fid ORDER BY i.timestamp DESC, i.iid DESC;
SELECT COUNT(dst) FROM url_alias WHERE dst = '%s';
SELECT * FROM access WHERE status = 1 AND type = '%s' AND LOWER('%s') = LOWER(mask);
SELECT u.* FROM users u WHERE u.status < 3;
SELECT * FROM boxes WHERE bid = 0;
SELECT * FROM book WHERE nid = 0;
SELECT parent, weight, log FROM book WHERE nid = 0;
SELECT data, created, headers FROM cache WHERE cid = '%s';
SELECT cache FROM filter_formats WHERE format = 0;
SELECT comment_count FROM node_comment_statistics WHERE nid = 0;
SELECT COUNT(cid) FROM comments WHERE pid = 0 AND status = 0;
SELECT c.cid, c.title, f.fid FROM aggregator_category c LEFT JOIN aggregator_category_feed f ON c.cid = f.cid AND f.fid = 0 ORDER BY title;
SELECT cid FROM aggregator_category_feed WHERE fid = 0;
SELECT c.cid, c.title, ci.iid FROM aggregator_category c LEFT JOIN aggregator_category_item ci ON c.cid = ci.cid AND ci.iid = 0;
SELECT cid, title, block FROM aggregator_category WHERE cid = 0;
SELECT cid, title FROM aggregator_category WHERE cid = 0;
SELECT * FROM vocabulary WHERE nodes = '%s' or nodes = '%s,%%' or nodes = '%%,%s,%%' or nodes = '%%,%s' ORDER BY weight, name;
SELECT c.*, u.name AS registered_name, u.uid FROM comments c INNER JOIN users u ON u.uid = c.uid WHERE c.cid = 0;
SELECT c.*, u.uid, u.name AS registered_name, u.data FROM comments c INNER JOIN users u ON c.uid = u.uid WHERE c.cid = 0;
SELECT c.*, u.uid, u.name AS registered_name, u.picture, u.data FROM comments c INNER JOIN users u ON c.uid = u.uid WHERE c.cid = 0 AND c.status = 0;
SELECT c.*, u.uid, u.name AS registered_name, u.picture, u.data FROM comments c INNER JOIN users u ON c.uid = u.uid WHERE c.cid = 0 AND c.status = 0;
SELECT * FROM comments WHERE cid = 0;
SELECT comment FROM node WHERE nid = 0;
SELECT c.nid, c.timestamp, c.name, c.uid, COUNT(c.nid) as comment_count FROM comments c INNER JOIN node n ON c.nid = n.nid WHERE c.status = 0 GROUP BY c.nid;
SELECT COUNT(cid) FROM comments WHERE nid = 0 AND status = 0;
SELECT * FROM profile_fields WHERE fid = 0;
SELECT data FROM users WHERE uid = 0;
SELECT * FROM term_data WHERE LOWER('%s') = LOWER(name);
SELECT * FROM vocabulary WHERE LOWER('%s') = LOWER(name);
SELECT * FROM access WHERE status = 0 AND type = '%s' AND LOWER('%s') = LOWER(mask);
SELECT COUNT(cid) FROM comments WHERE pid = 0 AND nid = 0 AND subject = '%s' AND comment = '%s';
SELECT uid FROM users WHERE uid != 0 AND LOWER(mail) = LOWER('%s');
SELECT uid FROM users WHERE uid != 0 AND LOWER(name) = LOWER('%s');
SELECT COUNT(dst) FROM url_alias WHERE dst = '%s' AND src != '%s';
SELECT iid FROM aggregator_item WHERE fid = 0 AND link = '%s';
SELECT iid FROM aggregator_item WHERE fid = 0 AND title = '%s';
SELECT fid, title, block FROM aggregator_feed WHERE fid = 0;
SELECT * FROM aggregator_feed WHERE fid = 0;
SELECT fid, type, title, page, visibility FROM profile_fields WHERE name = '%s';
SELECT filter, fid, minimum FROM moderation_filters WHERE fid = 0;
SELECT * FROM filter_formats WHERE format = 0;
SELECT * FROM filter_formats WHERE format = 0;
SELECT * FROM forum WHERE nid = 0;
SELECT COUNT(sid) AS cnt FROM sessions WHERE timestamp >= 0 AND uid = 0;
SELECT timestamp FROM history WHERE uid = 0 AND nid = 0;
SELECT id FROM sequences WHERE name = '%s';
SELECT locale FROM locales_meta WHERE locale = '%s';
SELECT locale FROM locales_meta WHERE locale = '%s';
SELECT nid FROM node WHERE status = 1 AND moderate = 0 AND (created > 'variable_get');
SELECT COUNT(dst) FROM url_alias WHERE pid != 0 AND dst = '%s';
SELECT COUNT(*) FROM term_data WHERE tid = 0 AND vid = 0;
SELECT fid FROM profile_fields WHERE name = '%s';
SELECT fid FROM profile_fields WHERE title = '%s';
SELECT i.*, f.title as ftitle, f.link as flink FROM aggregator_item i, aggregator_feed f WHERE i.iid = 0 AND i.fid = f.fid;
SELECT MAX(cid) FROM comments;
SELECT MAX(cid) FROM comments;
SELECT MAX(nid) FROM node;
SELECT MAX(tid) FROM term_data;
SELECT MAX(vid) FROM vocabulary;
SELECT * FROM menu WHERE mid = 0;
SELECT i.title, i.timestamp, i.link FROM aggregator_item i WHERE i.fid = 0 ORDER BY i.timestamp DESC;
SELECT i.title, i.timestamp, i.link, f.title as feed_title, f.link as feed_link FROM aggregator_category_item ci LEFT JOIN aggregator_item i ON i.iid = ci.iid LEFT JOIN aggregator_feed f ON i.fid = f.fid WHERE ci.cid = 0 ORDER BY i.timestamp DESC;
SELECT s.source, s.location, s.lid, t.translation, t.locale FROM locales_source s INNER JOIN locales_target t ON s.lid = t.lid;
SELECT cid, name, timestamp, uid FROM comments WHERE nid = 0 AND status = 0 ORDER BY cid DESC;
SELECT lid FROM locales_source WHERE location = '%s' AND source = '%s';
SELECT lid FROM locales_source WHERE source = '%s';
SELECT lid FROM locales_source WHERE source = '%s';
SELECT lid FROM locales_source WHERE source = '%s';
SELECT lid FROM locales_source WHERE source = '%s';
SELECT lid FROM locales_source WHERE source = '%s';
SELECT iid FROM aggregator_item ORDER BY iid DESC;
SELECT MAX(aid) FROM access;
SELECT MAX(thread) FROM comments WHERE nid = 0;
SELECT MAX(thread) FROM comments WHERE thread = '%s.%%' AND nid = 0;
SELECT * FROM locales_meta WHERE locale = '%s';
SELECT nid FROM comments WHERE cid = 0;
SELECT COUNT(*) AS strings FROM locales_source;
SELECT pid FROM url_alias WHERE dst = '%s';
SELECT * FROM book WHERE nid = 0;
SELECT * FROM comments WHERE cid = 0;
SELECT COUNT(src) FROM url_alias WHERE src = '%s';
SELECT runtime, voters, active FROM poll WHERE nid = 0;
SELECT * FROM filter_formats;
SELECT COUNT(url) FROM accesslog WHERE url <> '';
SELECT COUNT(url) FROM accesslog WHERE url <> '' AND url = '%check_query%';
SELECT COUNT(url) FROM accesslog WHERE url <> '' AND url <> '%check_query';
SELECT c.cid as cid, c.pid, c.nid, c.subject, c.comment, c.format, c.timestamp, c.name , c.mail, c.homepage, u.uid, u.name AS registered_name, u.picture, u.data, c.score, c.users, c.thread FROM comments c INNER JOIN users u ON c.uid = u.uid WHERE c.nid = 'check_query' AND c.status = 0;
SELECT url, MAX(timestamp) AS last_hit, COUNT(url) AS hits FROM accesslog WHERE url <> '' GROUP BY url;
SELECT url, MAX(timestamp) AS last_hit, COUNT(url) AS hits FROM accesslog WHERE url = '%check_query%' GROUP BY url;
SELECT url, MAX(timestamp) AS last_hit, COUNT(url) AS hits FROM accesslog WHERE url <> '%check_query%' AND url <> '' GROUP BY url;
SELECT COUNT(timestamp) AS hits FROM accesslog WHERE timestamp >= 0;
SELECT COUNT(timestamp) AS hits FROM accesslog WHERE timestamp >= 0;
SELECT nid FROM book WHERE format = 1;
SELECT nid FROM page WHERE format = 1;
SELECT rid FROM permission WHERE perm = '%create php content%';
SELECT cid, pid FROM comments WHERE nid = '0' ORDER BY timestamp;
SELECT n.nid, t.tid FROM node n, term_node t WHERE n.nid = t.nid AND type = 'forum';
SELECT * FROM aggregator_item WHERE fid = 0 ORDER BY timestamp DESC, iid DESC;
SELECT * FROM comments WHERE status = 0 ORDER BY timestamp DESC;
SELECT * FROM users WHERE LOWER(name) = '%%%s%%';
SELECT i.* FROM aggregator_category_item ci LEFT JOIN aggregator_item i ON ci.iid = i.iid WHERE ci.cid = 0 ORDER BY i.timestamp DESC, i.iid DESC;
SELECT n.nid, n.title FROM node_counter s INNER JOIN node n ON s.nid = n.nid; 
SELECT uid, name FROM users WHERE status != 0 ORDER BY uid DESC;
SELECT u.*, s.* FROM users u INNER JOIN sessions s ON u.uid = s.uid WHERE s.sid = '%s' AND u.status < 3;
SELECT authname FROM authmap WHERE uid = 0 AND module = '%s';
SELECT authname, module FROM authmap WHERE authname = '%s';
SELECT bid, format FROM boxes;
SELECT bid, title, info FROM boxes ORDER BY title;
SELECT c.cid, c.pid, c.nid, c.subject, c.comment, c.format, c.timestamp, c.name, c.mail, c.homepage, u.uid, u.name AS registered_name, u.picture, u.data, c.score, c.users FROM comments c INNER JOIN users u ON c.uid = u.uid WHERE c.cid = 0 AND c.status = 0 GROUP BY c.cid, c.pid, c.nid, c.subject, c.comment, c.timestamp, c.name, c.mail, u.picture, c.homepage, u.uid, u.name, u.picture, u.data, c.score, c.users;
SELECT c.cid, c.title, c.description FROM aggregator_category c LEFT JOIN aggregator_category_item ci ON c.cid = ci.cid LEFT JOIN aggregator_item i ON ci.iid = i.iid GROUP BY c.cid, c.title, c.description;
SELECT c.cid, c.title, count(ci.iid) as items FROM aggregator_category c LEFT JOIN aggregator_category_item ci ON c.cid = ci.cid GROUP BY c.cid, c.title ORDER BY title;
SELECT chtext, chvotes, chorder FROM poll_choices WHERE nid=0 ORDER BY chorder;
SELECT cid, title FROM aggregator_category WHERE block != 0 ORDER BY title;
SELECT COUNT(*) from authmap WHERE uid != 0 AND authname = '%s';
SELECT COUNT(nid) FROM node WHERE moderate = 1;
SELECT c.title, c.cid FROM aggregator_category_item ci LEFT JOIN aggregator_category c ON ci.cid = c.cid WHERE ci.iid = 0 ORDER BY c.title;
SELECT c.*, u.name AS registered_name, u.uid FROM comments c INNER JOIN users u ON c.uid = u.uid WHERE c.cid = 0;
SELECT c.*, u.name AS registered_name, u.uid FROM comments c INNER JOIN users u ON u.uid = c.uid WHERE pid = 0;
SELECT category FROM profile_fields;
 SELECT mid, value, value FROM moderation_roles WHERE rid IN (0,1) ORDER BY mid, value, value;
SELECT nid FROM comments WHERE thread = '';
SELECT p.perm FROM role r INNER JOIN permission p ON p.rid = r.rid INNER JOIN users_roles ur ON ur.rid = r.rid WHERE ur.uid = 0;
SELECT  s.source, t.translation, t.locale FROM locales_source s INNER JOIN locales_target t ON s.lid = t.lid WHERE s.lid = 0;
SELECT type FROM watchdog;
SELECT ur1.uid FROM users_roles ur1 LEFT JOIN users_roles ur2 ON ur2.uid = ur1.uid WHERE ur1.rid = 0 AND ur2.rid != ur1.rid;
SELECT u.uid FROM comments c LEFT JOIN users u ON c.uid = u.uid WHERE c.timestamp < u.created;
SELECT u.uid FROM node n LEFT JOIN users u ON n.uid = u.uid WHERE n.created < u.created;
SELECT f.*, COUNT(i.iid) AS items FROM aggregator_feed f LEFT JOIN aggregator_item i ON f.fid = i.fid GROUP BY f.fid, f.title, f.url, f.refresh, f.checked, f.link, f.description, f.etag, f.modified, f.image, f.block ORDER BY f.title;
SELECT f.fid, f.title, f.description, f.image, MAX(i.timestamp) AS last FROM aggregator_feed f LEFT JOIN aggregator_item i ON f.fid = i.fid GROUP BY f.fid;
SELECT fid, filter FROM moderation_filters ;
SELECT fid, filter FROM moderation_filters ;
SELECT fid, filter, minimum FROM moderation_filters ORDER BY minimum;
SELECT fid, name, type FROM profile_fields WHERE LOWER(category) = LOWER('%s');
SELECT fid, name, type FROM profile_fields WHERE register = 1 ORDER BY category, weight;
SELECT fid, title FROM aggregator_feed WHERE block != 0 ORDER BY fid;
SELECT filename, type, status, throttle FROM system WHERE type = '%s';
SELECT f.name, f.type, v.value FROM profile_fields f INNER JOIN profile_values v ON f.fid = v.fid WHERE uid = 0;
SELECT * FROM access WHERE type = '%s' AND status = 0 ORDER BY mask;
SELECT * FROM access WHERE type = '%s' AND status = 1 ORDER BY mask;
SELECT * FROM aggregator_feed ORDER BY title;
SELECT * FROM aggregator_feed WHERE checked + refresh < 0;
SELECT * FROM blocks;
SELECT * FROM blocks WHERE custom = 0 ORDER BY module, delta;
SELECT * FROM blocks WHERE (status = 1 OR custom = 1) AND region = 0;
SELECT * FROM directory ; 
SELECT * FROM files WHERE nid = 0;
SELECT * FROM filters;
SELECT * FROM filters WHERE format = 0 ORDER BY weight ASC;
SELECT * FROM menu ORDER BY mid ASC;
SELECT * FROM profile_fields ORDER BY category, weight;
SELECT * FROM profile_fields ORDER BY category, weight;
SELECT * FROM profile_fields WHERE LOWER(category) = LOWER('%s') ORDER BY weight;
SELECT * FROM profile_fields WHERE LOWER(category) = LOWER('%s') ORDER BY weight;
SELECT * FROM profile_fields WHERE register = 1 ORDER BY category, weight;
SELECT * FROM profile_fields WHERE register = 1 ORDER BY category, weight;
SELECT * FROM profile_fields WHERE visibility != 0 ORDER BY category, weight;
SELECT * FROM role ;
SELECT * FROM role ORDER BY name;
SELECT * FROM role ORDER BY name;
SELECT * FROM system WHERE type = 'theme_engine' AND status = '1' ORDER BY name;
SELECT * FROM system WHERE type = 'theme' ORDER BY name;
SELECT * FROM url_alias;
SELECT * FROM users WHERE uid = 1;
SELECT * FROM variable;
SELECT * FROM variable WHERE name = 'node_static_%';
SELECT * FROM variable WHERE name = 'update_start' AND value = '%';
SELECT * FROM variable WHERE value <> 's';
SELECT * FROM vocabulary ORDER BY weight, name;
SELECT * FROM vocabulary WHERE nodes = '%s' or nodes = '%s,%%' or nodes = '%%,%s,%%' or nodes = '%%,%s' ORDER BY weight, name;
SELECT iid FROM aggregator_item WHERE fid = 0 AND timestamp < 0;
SELECT iid FROM aggregator_item WHERE fid = 0;
SELECT iid FROM aggregator_item WHERE fid = 0;
SELECT lid FROM locales_source;
SELECT lid, source FROM locales_source WHERE source = '%s';
SELECT locale, name, formula, enabled FROM locales_meta ORDER BY isdefault DESC, enabled DESC, name ASC;
SELECT mid, vote FROM moderation_votes ORDER BY weight;
SELECT mid, vote, weight FROM moderation_votes ORDER BY weight;
SELECT name, filename, throttle, bootstrap FROM system WHERE type = 'module' AND status = 1;
SELECT name, filename, throttle, bootstrap FROM system WHERE type = 'module' AND status = 1 AND bootstrap = 1;
SELECT name FROM term_data WHERE tid IN (0,1);
SELECT name FROM term_synonym WHERE tid = 0;
SELECT name, title, type FROM profile_fields WHERE fid != 0 AND visibility = 0;
SELECT name, title, type FROM profile_fields WHERE visibility = 0;
SELECT nid, timestamp FROM history WHERE uid = 0;
SELECT pid, src FROM url_alias WHERE src = '%s%%';
SELECT pid, src FROM url_alias WHERE src = 'taxonomy/%%';
SELECT p.nid FROM poll p INNER JOIN node n ON p.nid=n.nid WHERE (n.created + p.runtime) < 'time()' AND p.active = '1' AND p.runtime != '0';
SELECT r.* FROM role r INNER JOIN permission p ON r.rid = p.rid WHERE p.perm = '%%%s%%' ORDER BY r.name;
SELECT rid, mid, value FROM moderation_roles;
SELECT rid, name FROM role ORDER BY name;
SELECT r.rid, p.perm FROM role r LEFT JOIN permission p ON r.rid = p.rid ORDER BY name;
SELECT r.rid, r.name FROM role r INNER JOIN users_roles ur ON ur.rid = r.rid WHERE ur.uid = 0;
SELECT r.rid, r.name FROM role r INNER JOIN users_roles ur ON ur.rid = r.rid WHERE ur.uid = 0;
SELECT r.rid, r.name FROM role r, permission p WHERE r.rid = p.rid AND p.perm = '%moderate comments%';
SELECT r.rid, r.name FROM role r, permission p WHERE r.rid = p.rid AND p.perm = '%post comments%';
SELECT score FROM node WHERE nid = 0;
SELECT s.lid, s.source, s.location, t.plid, t.plural FROM locales_source s INNER JOIN locales_target t ON s.lid = t.lid GROUP BY s.lid ORDER BY t.plid, t.plural;
SELECT s.lid, s.source, s.location, t.translation, t.plid, t.plural FROM locales_source s INNER JOIN locales_target t ON s.lid = t.lid WHERE t.locale = '%s' ORDER BY t.plid, t.plural;
SELECT s.lid, t.translation FROM locales_source s INNER JOIN locales_target t ON s.lid = t.lid WHERE s.source = '%s' AND t.locale = '%s';
SELECT s.source, t.translation, t.locale FROM locales_source s INNER JOIN locales_target t ON s.lid = t.lid WHERE t.locale = '%s' AND LENGTH(s.source) < 75;
SELECT SUM(f.filesize) FROM files f INNER JOIN node n ON f.nid = n.nid;
SELECT SUM(f.filesize) FROM files f INNER JOIN node n ON f.nid = n.nid WHERE uid = 0;
SELECT t.* FROM term_data t, term_node r WHERE r.tid = t.tid AND r.nid = 0 ORDER BY weight, name;
SELECT t.* FROM term_data t, term_node r WHERE t.tid = r.tid AND t.vid = 0 AND r.nid = 0 ORDER BY weight;
SELECT t.* FROM term_hierarchy h, term_data t WHERE h.parent = t.tid AND h.tid = 0 ORDER BY weight, name;
SELECT t.* FROM term_hierarchy h, term_data t WHERE h.tid = t.tid AND parent = 0 ORDER BY weight;
SELECT t.* FROM term_hierarchy h, term_data t WHERE t.vid = 0 AND h.tid = t.tid AND h.parent = 0 ORDER BY weight, name;
SELECT tid FROM term_data WHERE vid = 0;
SELECT tid, parent FROM term_hierarchy;
SELECT title, cid FROM aggregator_category ORDER BY title;
SELECT title, fid FROM aggregator_feed ORDER BY title;
SELECT t.*, parent FROM term_data t, term_hierarchy h WHERE t.tid = h.tid AND t.vid = 0 ORDER BY weight, name;
SELECT t.*, tid1, tid2 FROM term_relation, term_data t WHERE (t.tid = tid1 OR t.tid = tid2) AND (tid1 = 0 OR tid2 = 0) AND t.tid != 0 ORDER BY weight, name;
SELECT u.* FROM users u WHERE u.uid = 0;
SELECT uid FROM authmap WHERE authname = '%s';
SELECT uid FROM users WHERE data = '%profile%';
SELECT uid FROM users WHERE uid > 0;
SELECT v.mid, v.vote, MAX(v.weight) AS weight, MAX(r.value) AS value FROM moderation_votes v INNER JOIN moderation_roles r ON r.mid = v.mid WHERE r.rid IN (0,1) GROUP BY v.mid, v.vote ORDER BY weight;
SELECT w.*, u.name, u.uid FROM watchdog w INNER JOIN users u ON w.uid = u.uid WHERE w.wid = 0;
SELECT COUNT(c.cid) FROM node n INNER JOIN comments c ON n.nid = c.nid WHERE n.nid = 0 AND timestamp > 0 AND c.status = 0;
SELECT COUNT(*) FROM comments WHERE status = 0 AND nid = 0;
SELECT n.*, u.name, u.uid FROM node n INNER JOIN users u ON n.uid = u.uid;
SELECT uid FROM users WHERE uid > 0 ORDER BY changed DESC;
SELECT u.uid FROM users u INNER JOIN profile_values v ON u.uid = v.uid WHERE v.fid = 0 ORDER BY u.changed DESC;
SELECT n.nid, 0, NULL, 0, 0 FROM node n;
SELECT c.cid as lno, c.subject as text1, c.comment as text2 FROM comments c WHERE c.status = 0 AND timestamp > '';
SELECT * FROM aggregator_category WHERE cid = 0;
SELECT * FROM aggregator_feed WHERE fid = 0;
SELECT * FROM boxes WHERE bid = 0;
SELECT * FROM url_alias WHERE pid = 0;
SELECT last_comment_timestamp, last_comment_name, comment_count FROM node_comment_statistics WHERE nid = 0;
SELECT * FROM term_data WHERE tid = 0;
SELECT * FROM term_synonym s, term_data t WHERE t.tid = s.tid AND s.name = '%s';
SELECT * FROM vocabulary WHERE vid = 0;
SELECT link, description FROM page WHERE nid = 0;
SELECT s.nid, n.title, u.uid, u.name FROM node_counter s INNER JOIN node n ON s.nid = n.nid INNER JOIN users u ON n.uid = u.uid AND n.status = 1 ; 
SELECT COUNT(n.nid) FROM node n WHERE n.nid = 0 AND ((n.title = '%%%s%%') OR (n.body = '%%%s%%'));
SELECT rid FROM role WHERE name = 'authenticated user';
SELECT * FROM role WHERE rid = 0;
SELECT r.name FROM role r INNER JOIN users_roles ur ON ur.rid = r.rid WHERE ur.uid = 0;
SELECT n.nid as lno, n.title as text1, n.body as text2 FROM node n WHERE n.status = 1 AND moderate = 0 and (created > '');
SELECT nid,tid FROM forum WHERE shadow=0;
SELECT COUNT(hostname) FROM accesslog;
SELECT COUNT(title) FROM accesslog WHERE title <> '';
SELECT COUNT(uid) FROM accesslog;
SELECT COUNT(*) FROM node_access WHERE (nid = 0 OR nid = 0) AND realm IN (0,1) AND gid IN (0,1);
SELECT c.subject, c.nid, c.cid, c.comment, c.timestamp, c.status, c.name, c.homepage, u.name AS registered_name, u.uid FROM comments c INNER JOIN users u ON u.uid = c.uid WHERE c.status = 'check_query($status)';
SELECT * FROM url_alias;
SELECT hostname, uid, MAX(timestamp) AS last_hit, COUNT(hostname) AS hits FROM accesslog GROUP BY hostname, uid;
SELECT s.nid, s.daycount, s.totalcount, s.timestamp, n.title FROM node_counter s INNER JOIN node n ON s.nid = n.nid;
SELECT title, path, MAX(timestamp) AS last_hit, COUNT(title) AS hits FROM accesslog WHERE title <> '' GROUP BY title, path;
SELECT title, path, url, hostname, uid, MAX(timestamp) AS timestamp FROM accesslog WHERE uid <> 0 GROUP BY uid, title, path, url, hostname;
SELECT title, path, url, hostname, uid, timestamp FROM accesslog;
SELECT title, path, url, hostname, uid, timestamp FROM accesslog WHERE title = '';
SELECT title, path, url, hostname, uid, timestamp FROM accesslog WHERE uid = '';
SELECT title, path, url, hostname, uid, timestamp, title FROM accesslog WHERE hostname = '';
SELECT uid, hostname, MAX(timestamp) AS last_hit, COUNT(uid) AS hits FROM accesslog GROUP BY uid, hostname;
SELECT u.uid, u.name, u.status, u.changed FROM users u WHERE uid != 0;
SELECT w.*, u.name, u.uid FROM watchdog w INNER JOIN users u ON w.uid = u.uid;
SELECT n.*, u.name, u.uid FROM node n INNER JOIN users u ON n.uid = u.uid WHERE n.moderate = 1;
SELECT totalcount, daycount, timestamp FROM node_counter WHERE nid = 0;
SELECT isdefault, enabled FROM locales_meta WHERE locale = '%s';
SELECT COUNT(uid) FROM users WHERE LOWER(name) = '%s';
SELECT name FROM term_data WHERE tid = 0;
SELECT minimum FROM moderation_filters WHERE fid = 0;
SELECT MIN(created) FROM node WHERE uid = 0;
SELECT MIN(timestamp) FROM comments WHERE uid = 0;
SELECT title FROM node WHERE nid = 0;
SELECT lid, translation, plid, plural FROM locales_target WHERE lid = 0 AND locale = '%s';
SELECT lid, translation FROM locales_target WHERE lid = 0 AND locale = '%s';
SELECT translation FROM locales_target WHERE lid = 0 AND locale = '%s';
SELECT COUNT(*) AS translation FROM locales_target WHERE locale = '%s' AND translation != '';
SELECT uid, MAX(timestamp) AS max_timestamp FROM sessions WHERE timestamp >= 0 AND uid != 0 GROUP BY uid ORDER BY max_timestamp DESC;
SELECT MAX(uid) FROM users;
SELECT vote, weight FROM moderation_votes WHERE mid = 0;
SELECT weight FROM book WHERE nid = 0;