SELECT i.*, f.title AS ftitle, f.link AS flink FROM aggregator_category_item c LEFT JOIN aggregator_item i ON c.iid = i.iid LEFT JOIN aggregator_feed f ON i.fid = f.fid WHERE cid = '. $category->cid .' ORDER BY timestamp DESC, iid DESC;
SELECT i.*, f.title AS ftitle, f.link AS flink FROM aggregator_item i INNER JOIN aggregator_feed f ON i.fid = f.fid ORDER BY i.timestamp DESC, i.iid DESC;
SELECT COUNT(dst) FROM url_alias WHERE dst = '%s';
SELECT * FROM access WHERE status = 1 AND type = '%s' AND LOWER('%s') = LOWER(mask);
SELECT n.nid, n.title, n.created FROM node n WHERE n.type = 'blog' AND n.status = 1 ORDER BY n.created DESC;
SELECT * FROM boxes WHERE bid = 0;
SELECT * FROM book WHERE nid = 0;
SELECT parent, weight, log FROM book WHERE nid = 0;
SELECT data, created, headers FROM cache WHERE cid = '%s';
SELECT cache FROM filter_formats WHERE format = 0;
SELECT comment_count FROM node_comment_statistics WHERE nid = 0;
SELECT COUNT(cid) FROM comments WHERE pid = 0 AND status = 0;
SELECT c.cid, c.title, f.fid FROM aggregator_category c LEFT JOIN aggregator_category_feed f ON c.cid = f.cid AND f.fid = 0 ORDER BY title;
SELECT cid FROM aggregator_category_feed WHERE fid = 0;
SELECT c.cid, c.title, ci.iid FROM aggregator_category c LEFT JOIN aggregator_category_item ci ON c.cid = ci.cid AND ci.iid = 0;
SELECT cid, title FROM aggregator_category WHERE cid = 0;
SELECT v.*, n.type FROM vocabulary v INNER JOIN vocabulary_node_types n ON v.vid = n.vid WHERE n.type = '%s' ORDER BY v.weight, v.name;
SELECT n.nid, n.title, b.weight FROM node n INNER JOIN book b ON n.nid = b.nid WHERE b.parent = 0 AND n.status = 1 AND n.moderate = 0 ORDER BY b.weight ASC, n.title ASC;
SELECT c.*, u.name AS registered_name, u.uid FROM comments c INNER JOIN users u ON u.uid = c.uid WHERE c.cid = 0;
SELECT c.*, u.uid, u.name AS registered_name, u.data FROM comments c INNER JOIN users u ON c.uid = u.uid WHERE c.cid = 0;
SELECT c.*, u.uid, u.name AS registered_name, u.picture, u.data FROM comments c INNER JOIN users u ON c.uid = u.uid WHERE c.cid = 0 AND c.status = 0;
SELECT c.*, u.uid, u.name AS registered_name, u.picture, u.data FROM comments c INNER JOIN users u ON c.uid = u.uid WHERE c.cid = 0 AND c.status = 0;
SELECT * FROM comments WHERE cid = 0;
SELECT comment FROM node WHERE nid = 0;
SELECT subject, comment, format FROM comments WHERE nid = 0 AND status = 0;
SELECT comment_count FROM node_comment_statistics WHERE nid = 0;
SELECT COUNT(cid) FROM comments WHERE nid = 0 AND status = 0;
SELECT COUNT(cid) FROM comments WHERE nid = 0 AND status = 0;
SELECT * FROM profile_fields WHERE fid = 0;
SELECT data FROM users WHERE uid = 0;
SELECT * FROM term_data WHERE LOWER('%s') = LOWER(name);
SELECT * FROM access WHERE status = 0 AND type = '%s' AND LOWER('%s') = LOWER(mask);
SELECT n.nid, n.title, b.weight FROM node n INNER JOIN book b ON n.nid = b.nid WHERE b.parent = 0 AND n.status = 1 AND n.moderate = 0 AND (b.weight < 0 OR (b.weight = 0 AND n.title < '%s')) ORDER BY b.weight DESC, n.title DESC;
SELECT COUNT(cid) FROM comments WHERE pid = 0 AND nid = 0 AND subject = '%s' AND comment = '%s';
SELECT aid, type, status, mask FROM access WHERE aid = 0;
SELECT pages, visibility, custom, types FROM blocks WHERE module = '%s' AND delta = '%s';
SELECT aid, type, status, mask FROM access WHERE aid = 0;
SELECT uid FROM users WHERE uid != 0 AND LOWER(mail) = LOWER('%s');
SELECT uid FROM users WHERE uid != 0 AND LOWER(name) = LOWER('%s');
SELECT COUNT(dst) FROM url_alias WHERE dst = '%s' AND src != '%s';
SELECT nid FROM node WHERE nid = 0;
SELECT nid FROM node WHERE nid = 0;
SELECT filename FROM system WHERE name = '%s' AND type = '%s';
SELECT iid FROM aggregator_item WHERE fid = 0 AND link = '%s';
SELECT iid FROM aggregator_item WHERE fid = 0 AND title = '%s';
SELECT COUNT(*) FROM search_total WHERE word = '%s';
SELECT * FROM aggregator_feed WHERE fid = 0;
SELECT (fid), type, title, page, visibility FROM profile_fields WHERE name = '%s';
SELECT filter, fid, minimum FROM moderation_filters WHERE fid = 0;
SELECT * FROM filter_formats WHERE format = 0;
SELECT * FROM filter_formats WHERE format = 0;
SELECT * FROM forum WHERE nid = 0;
SELECT COUNT(sid) AS cnt FROM sessions WHERE timestamp >= 0 AND uid = 0;
SELECT COUNT(sid) AS cnt FROM sessions WHERE timestamp >= 0 AND uid = 0;
SELECT timestamp FROM history WHERE uid = 0 AND nid = 0;
SELECT id FROM sequences WHERE name = '%s';
SELECT cid, title, block FROM aggregator_category WHERE cid = 0;
SELECT locale FROM locales_meta WHERE locale = '%s';
SELECT locale FROM locales_meta WHERE locale = '%s';
SELECT nid FROM node WHERE status = 1 AND moderate = 0 AND (created > 'variable_get' OR changed > 'variable_get');
SELECT COUNT(dst) FROM url_alias WHERE pid != 0 AND dst = '%s';
SELECT COUNT(*) FROM term_data WHERE tid = 0 AND vid = 0;
SELECT fid FROM profile_fields WHERE name = '%s';
SELECT fid FROM profile_fields WHERE title = '%s' AND category = '%s';
SELECT fid, title, block FROM aggregator_feed WHERE fid = 0;
SELECT i.*, f.title as ftitle, f.link as flink FROM aggregator_item i, aggregator_feed f WHERE i.iid = 0 AND i.fid = f.fid;
SELECT MAX(cid) FROM comments;
SELECT MAX(cid) FROM comments;
SELECT MAX(nid) FROM node;
SELECT MAX(tid) FROM term_data;
SELECT MAX(vid) FROM vocabulary;
SELECT * FROM menu WHERE mid = 0;
SELECT i.title, i.timestamp, i.link FROM aggregator_item i WHERE i.fid = 0 ORDER BY i.timestamp DESC;
SELECT i.title, i.timestamp, i.link, f.title as feed_title, f.link as feed_link FROM aggregator_category_item ci LEFT JOIN aggregator_item i ON i.iid = ci.iid LEFT JOIN aggregator_feed f ON i.fid = f.fid WHERE ci.cid = 0 ORDER BY i.timestamp DESC;
SELECT s.source, s.location, s.lid, t.translation, t.locale FROM locales_source s INNER JOIN locales_target t ON s.lid = t.lid;
SELECT n.nid, n.title, b.parent, b.weight FROM node n INNER JOIN book b ON n.nid = b.nid WHERE n.status = 1 AND b.parent = 0 ORDER BY b.weight DESC, n.title DESC;
SELECT cid, name, timestamp, uid FROM comments WHERE nid = 0 AND status = 0 ORDER BY cid DESC;
SELECT lid FROM locales_source WHERE location = '%s' AND source = '%s';
SELECT lid FROM locales_source WHERE source = '%s';
SELECT lid FROM locales_source WHERE source = '%s';
SELECT lid FROM locales_source WHERE source = '%s';
SELECT lid FROM locales_source WHERE source = '%s';
SELECT lid FROM locales_source WHERE source = '%s';
SELECT iid FROM aggregator_item ORDER BY iid DESC;
SELECT MAX(aid) FROM access;
SELECT MAX(thread) FROM comments WHERE nid = 0;
SELECT MAX(thread) FROM comments WHERE thread = '%s.%%' AND nid = 0;
SELECT * FROM locales_meta WHERE locale = '%s';
SELECT n.nid, n.title, b.weight FROM node n INNER JOIN book b ON n.nid = b.nid WHERE b.parent = 0 AND n.status = 1 AND n.moderate = 0 AND (b.weight > 0 OR (b.weight = 0 AND n.title > '%s')) ORDER BY b.weight ASC, n.title ASC;
SELECT changed FROM node WHERE nid = 0;
SELECT nid FROM comments WHERE cid = 0;
SELECT n.nid FROM node n WHERE n.promote = 1 AND n.status = 1 ORDER BY n.created DESC;
SELECT event FROM flood WHERE event = '%s' AND hostname = '%s' AND timestamp > 0;
SELECT COUNT(*) AS strings FROM locales_source;
SELECT pid FROM url_alias WHERE dst = '%s';
SELECT * FROM book WHERE nid = 0;
SELECT n.nid, n.title, b.parent, b.weight FROM node n INNER JOIN book b ON n.nid = b.nid WHERE n.nid = 0;
SELECT * FROM comments WHERE cid = 0;
SELECT COUNT(src) FROM url_alias WHERE src = '%s';
SELECT runtime, polled, active FROM poll WHERE nid = 0;
SELECT n.nid, n.title FROM node n INNER JOIN book b ON n.nid = b.nid WHERE n.nid = 0 AND n.status = 1 AND n.moderate = 0;
SELECT COUNT((url)) FROM accesslog WHERE url <> '' AND url <> '%%%s%%';
SELECT c.cid as cid, c.pid, c.nid, c.subject, c.comment, c.format, c.timestamp, c.name , c.mail, c.homepage, u.uid, u.name AS registered_name, u.picture, u.data, c.score, c.users, c.thread FROM comments c INNER JOIN users u ON c.uid = u.uid WHERE c.nid = 0 AND c.status = 0;
SELECT * FROM filter_formats;
SELECT url, COUNT(url) AS hits, MAX(timestamp) AS last FROM accesslog WHERE url <> '%%%s%%' AND url <> '' GROUP BY url;
SELECT COUNT(*) FROM node n LEFT JOIN node_comment_statistics c ON n.nid = c.nid WHERE n.status = 1 AND n.moderate = 0 AND (n.created > 0 OR n.changed > 0 OR c.last_comment_timestamp > 0);
SELECT rid FROM permission WHERE perm = '%create php content%';
SELECT cid, pid FROM comments WHERE nid = '%d' ORDER BY timestamp;
SELECT n.nid, b.weight, n.title FROM node n INNER JOIN book b ON n.nid = b.nid WHERE b.parent = 0 AND n.status = 1 AND n.moderate = 0 ORDER BY b.weight, n.title;
SELECT n.nid, b.weight, n.title FROM node n INNER JOIN book b ON n.nid = b.nid WHERE b.parent = 0 ORDER BY b.weight, n.title;
SELECT n.nid FROM node n WHERE n.nid = 0 AND n.type != 'book';
SELECT n.nid, n.title, b.parent, b.weight FROM node n INNER JOIN book b ON n.nid = b.nid WHERE n.status = 1 AND n.moderate = 0 ORDER BY b.weight, n.title;
SELECT n.nid, n.title, b.parent, b.weight FROM node n INNER JOIN book b ON n.nid = b.nid WHERE n.status = 1 ORDER BY b.weight, n.title;
SELECT n.nid, n.title, b.parent FROM node n INNER JOIN book b ON n.nid = b.nid WHERE n.nid = 0;
SELECT n.nid, n.title, b.weight FROM node n INNER JOIN book b ON n.nid = b.nid WHERE b.parent = 0 ORDER BY b.weight, n.title;
SELECT n.nid, n.title, b.weight FROM node n INNER JOIN book b ON n.nid = b.nid WHERE n.status = 1 AND b.parent = 0 AND n.moderate = 0 ORDER BY b.weight, n.title;
SELECT n.nid, n.title, b.weight FROM node n INNER JOIN book b ON n.nid = b.nid WHERE n.status = 1 AND n.nid = 0 AND n.moderate = 0 ORDER BY b.weight, n.title;
SELECT n.nid, n.title, n.status, b.parent FROM node n INNER JOIN book b ON n.nid = b.nid;
SELECT t.tid, COUNT(n.nid) AS c FROM term_node t INNER JOIN node n ON t.nid = n.nid WHERE n.status = 1 GROUP BY t.tid;
SELECT t.tid, COUNT(n.nid) AS c FROM term_node t, node n WHERE t.nid = n.nid AND n.status = 1 AND n.type = '%s' GROUP BY t.tid;
SELECT n.nid, t.tid FROM node n, term_node t WHERE n.nid = t.nid AND type = 'forum';
SELECT c.nid, c.* FROM comments c WHERE c.status = 0 ORDER BY c.timestamp DESC;
SELECT n.nid, n.title, n.teaser, n.created, u.name, u.uid FROM node n INNER JOIN users u ON n.uid = u.uid WHERE n.type = 'blog' AND n.status = 1 ORDER BY n.created DESC;
SELECT n.nid, n.title, n.teaser, n.created, u.name, u.uid FROM node n INNER JOIN users u ON n.uid = u.uid WHERE n.type = 'blog' AND u.uid = 0 AND n.status = 1 ORDER BY n.created DESC;
SELECT * FROM aggregator_item WHERE fid = 0 ORDER BY timestamp DESC, iid DESC;
SELECT i.* FROM aggregator_category_item ci LEFT JOIN aggregator_item i ON ci.iid = i.iid WHERE ci.cid = 0 ORDER BY i.timestamp DESC, i.iid DESC;
SELECT n.nid, c.last_comment_timestamp FROM node n LEFT JOIN node_comment_statistics c ON n.nid = c.nid WHERE n.status = 1 AND n.moderate = 0 AND (n.created > 0 OR n.changed > 0 OR c.last_comment_timestamp > 0) ORDER BY n.created, n.changed, c.last_comment_timestamp ASC;
SELECT u.* FROM users u WHERE u.status < 3;
SELECT uid, name FROM users WHERE status != 0 ORDER BY uid DESC;
SELECT u.*, s.* FROM users u INNER JOIN sessions s ON u.uid = s.uid WHERE s.sid = '%s' AND u.status < 3;
SELECT aid, type, status, mask FROM access;
SELECT a.*, u.name FROM accesslog a LEFT JOIN users u ON a.uid = u.uid WHERE aid = 0;
SELECT authname FROM authmap WHERE uid = 0 AND module = '%s';
SELECT authname, module FROM authmap WHERE authname = '%s';
SELECT bid, title, info FROM boxes ORDER BY title;
SELECT c.cid, c.pid, c.nid, c.subject, c.comment, c.format, c.timestamp, c.name, c.mail, c.homepage, u.uid, u.name AS registered_name, u.picture, u.data, c.score, c.users FROM comments c INNER JOIN users u ON c.uid = u.uid WHERE c.cid = 0 AND c.status = 0 GROUP BY c.cid, c.pid, c.nid, c.subject, c.comment, c.format, c.timestamp, c.name, c.mail, u.picture, c.homepage, u.uid, u.name, u.picture, u.data, c.score, c.users;
SELECT c.cid, c.title, c.description FROM aggregator_category c LEFT JOIN aggregator_category_item ci ON c.cid = ci.cid LEFT JOIN aggregator_item i ON ci.iid = i.iid GROUP BY c.cid, c.title, c.description;
SELECT c.cid, c.title, count(ci.iid) as items FROM aggregator_category c LEFT JOIN aggregator_category_item ci ON c.cid = ci.cid GROUP BY c.cid, c.title ORDER BY title;
SELECT chtext, chvotes, chorder FROM poll_choices WHERE nid = 0 ORDER BY chorder;
SELECT cid, title FROM aggregator_category ORDER BY title;
SELECT c.nid, c.timestamp, c.name, c.uid, COUNT(c.nid) as comment_count FROM node n LEFT JOIN comments c ON c.nid = n.nid WHERE c.status = 0 GROUP BY c.nid, c.timestamp, c.name, c.uid;
SELECT COUNT(*) from authmap WHERE uid != 0 AND authname = '%s';
SELECT COUNT(nid) FROM node WHERE moderate = 1;
SELECT c.title, c.cid FROM aggregator_category_item ci LEFT JOIN aggregator_category c ON ci.cid = c.cid WHERE ci.iid = 0 ORDER BY c.title;
SELECT c.*, u.name AS registered_name, u.uid FROM comments c INNER JOIN users u ON c.uid = u.uid WHERE c.cid = 0;
SELECT c.*, u.name AS registered_name, u.uid FROM comments c INNER JOIN users u ON u.uid = c.uid WHERE pid = 0;
SELECT delta FROM blocks WHERE module = 'aggregator';
SELECT (category) FROM profile_fields;
SELECT (nid) FROM comments WHERE thread = '';
SELECT (p.perm) FROM role r INNER JOIN permission p ON p.rid = r.rid INNER JOIN users_roles ur ON ur.rid = r.rid WHERE ur.uid = 0;
SELECT  s.source, t.translation, t.locale FROM locales_source s INNER JOIN locales_target t ON s.lid = t.lid WHERE s.lid = 0;
SELECT (type) FROM watchdog ORDER BY type;
SELECT (ur1.uid) FROM users_roles ur1 LEFT JOIN users_roles ur2 ON ur2.uid = ur1.uid WHERE ur1.rid = 0 AND ur2.rid != ur1.rid;
SELECT (u.uid) FROM comments c LEFT JOIN users u ON c.uid = u.uid WHERE c.timestamp < u.created;
SELECT (u.uid) FROM node n LEFT JOIN users u ON n.uid = u.uid WHERE n.created < u.created;
SELECT f.*, COUNT(i.iid) AS items FROM aggregator_feed f LEFT JOIN aggregator_item i ON f.fid = i.fid GROUP BY f.fid, f.title, f.url, f.refresh, f.checked, f.link, f.description, f.etag, f.modified, f.image, f.block ORDER BY f.title;
SELECT f.fid, f.title, f.description, f.image, MAX(i.timestamp) AS last FROM aggregator_feed f LEFT JOIN aggregator_item i ON f.fid = i.fid GROUP BY f.fid, f.title, f.description, f.image;
SELECT fid, filter FROM moderation_filters ;
SELECT fid, filter FROM moderation_filters ;
SELECT fid, filter, minimum FROM moderation_filters ORDER BY minimum;
SELECT fid, name, type, category, weight FROM profile_fields WHERE register = 1 ORDER BY category, weight;
SELECT fid, name, type FROM profile_fields WHERE LOWER(category) = LOWER('%s');
SELECT fid, title FROM aggregator_feed ORDER BY fid;
SELECT f.name, f.type, v.value FROM profile_fields f INNER JOIN profile_values v ON f.fid = v.fid WHERE uid = 0;
SELECT f.nid, f.* FROM files f WHERE filepath = '%s';
SELECT * FROM aggregator_feed ORDER BY title;
SELECT * FROM aggregator_feed WHERE checked + refresh < 0;
SELECT * FROM blocks ;
SELECT * FROM blocks WHERE status = 1 AND custom != 0 ORDER BY weight, module, delta;
SELECT * FROM blocks WHERE status = 1 AND region IN (0,1) ORDER BY weight, module;
SELECT * FROM directory ; 
SELECT * FROM files WHERE nid = 0;
SELECT * FROM filters;
SELECT * FROM filters WHERE format = 0 ORDER BY weight ASC;
SELECT * FROM menu ORDER BY mid ASC;
SELECT * FROM profile_fields ORDER BY category, weight;
SELECT * FROM profile_fields ORDER BY category, weight;
SELECT * FROM profile_fields WHERE LOWER(category) = LOWER('%s') ORDER BY weight;
SELECT * FROM profile_fields WHERE LOWER(category) = LOWER('%s') ORDER BY weight;
SELECT * FROM profile_fields WHERE register = 1 ORDER BY category, weight;
SELECT * FROM profile_fields WHERE register = 1 ORDER BY category, weight;
SELECT * FROM profile_fields WHERE visibility != 0 ORDER BY category, weight;
SELECT * FROM role;
SELECT * FROM role ORDER BY name;
SELECT * FROM role ORDER BY name;
SELECT * FROM system WHERE type = 'theme_engine' AND status = '1' ORDER BY name;
SELECT * FROM system WHERE type = 'theme' ORDER BY name;
SELECT * FROM url_alias;
SELECT * FROM users WHERE uid = 1;
SELECT * FROM variable;
SELECT * FROM variable WHERE name = 'node_static_%';
SELECT * FROM variable WHERE name = 'update_start' AND value = '%';
SELECT * FROM variable WHERE value <> 's';
SELECT iid FROM aggregator_item WHERE fid = 0 AND timestamp < 0;
SELECT iid FROM aggregator_item WHERE fid = 0;
SELECT iid FROM aggregator_item WHERE fid = 0;
SELECT lid FROM locales_source;
SELECT lid, source FROM locales_source WHERE source = '%s';
SELECT locale, name, formula, enabled FROM locales_meta ORDER BY isdefault DESC, enabled DESC, name ASC;
SELECT mid, vote FROM moderation_votes ORDER BY weight;
SELECT mid, vote, weight FROM moderation_votes ORDER BY weight;
SELECT name, filename, throttle, bootstrap FROM system WHERE type = 'module' AND status = 1;
SELECT name, filename, throttle, bootstrap FROM system WHERE type = 'module' AND status = 1 AND bootstrap = 1;
SELECT name FROM term_synonym WHERE tid = 0;
SELECT name, title, type, weight FROM profile_fields WHERE fid != 0 AND visibility = 0 ORDER BY weight;
SELECT name, title, type, weight FROM profile_fields WHERE visibility = 0 ORDER BY weight;
SELECT name, type, status, throttle FROM system WHERE type = '%s';
SELECT nid, timestamp FROM history WHERE uid = 0;
SELECT pid, src FROM url_alias WHERE src = 'blog/%%';
SELECT pid, src FROM url_alias WHERE src = '%s%%';
SELECT pid, src FROM url_alias WHERE src = 'taxonomy/%%';
SELECT p.nid FROM poll p INNER JOIN node n ON p.nid = n.nid WHERE (n.created + p.runtime) < 'time()' AND p.active = 1 AND p.runtime != 0;
SELECT r.* FROM role r INNER JOIN permission p ON r.rid = p.rid WHERE p.perm = '%%%s%%' ORDER BY r.name;
SELECT rid, mid, value FROM moderation_roles;
SELECT rid, name FROM role ORDER BY name;
SELECT r.rid, p.perm FROM role r LEFT JOIN permission p ON r.rid = p.rid ORDER BY name;
SELECT r.rid, r.name FROM role r INNER JOIN users_roles ur ON ur.rid = r.rid WHERE ur.uid = 0;
SELECT r.rid, r.name FROM role r INNER JOIN users_roles ur ON ur.rid = r.rid WHERE ur.uid = 0;
SELECT r.rid, r.name FROM role r, permission p WHERE r.rid = p.rid AND p.perm = '%moderate comments%';
SELECT r.rid, r.name FROM role r, permission p WHERE r.rid = p.rid AND p.perm = '%post comments%';
SELECT s.lid, s.source, s.location, t.plid, t.plural FROM locales_source s INNER JOIN locales_target t ON s.lid = t.lid ORDER BY t.plid, t.plural;
SELECT s.lid, s.source, s.location, t.translation, t.plid, t.plural FROM locales_source s INNER JOIN locales_target t ON s.lid = t.lid WHERE t.locale = '%s' ORDER BY t.plid, t.plural;
SELECT s.lid, t.translation FROM locales_source s INNER JOIN locales_target t ON s.lid = t.lid WHERE s.source = '%s' AND t.locale = '%s';
SELECT s.source, t.translation, t.locale FROM locales_source s INNER JOIN locales_target t ON s.lid = t.lid WHERE t.locale = '%s' AND LENGTH(s.source) < 75;
SELECT SUM(f.filesize) FROM files f INNER JOIN node n ON f.nid = n.nid;
SELECT SUM(f.filesize) FROM files f INNER JOIN node n ON f.nid = n.nid WHERE uid = 0;
SELECT SUM(vote) FROM queue WHERE nid = 0;
SELECT t.* FROM term_data t, term_node r WHERE r.tid = t.tid AND r.nid = 0 ORDER BY weight, name;
SELECT t.* FROM term_data t, term_node r WHERE t.tid = r.tid AND t.vid = 0 AND r.nid = 0 ORDER BY weight;
SELECT t.* FROM term_hierarchy h, term_data t WHERE h.parent = t.tid AND h.tid = 0 ORDER BY weight, name;
SELECT t.* FROM term_hierarchy h, term_data t WHERE h.tid = t.tid AND parent = 0 ORDER BY weight;
SELECT t.* FROM term_hierarchy h, term_data t WHERE t.vid = 0 AND h.tid = t.tid AND h.parent = 0 ORDER BY weight, name;
SELECT tid FROM term_data WHERE vid = 0;
SELECT tid, parent FROM term_hierarchy;
SELECT title, cid FROM aggregator_category ORDER BY title;
SELECT title, fid FROM aggregator_feed ORDER BY title;
SELECT t.*, parent FROM term_data t, term_hierarchy h WHERE t.tid = h.tid AND t.vid = 0 ORDER BY weight, name;
SELECT t.*, tid1, tid2 FROM term_relation, term_data t WHERE (t.tid = tid1 OR t.tid = tid2) AND (tid1 = 0 OR tid2 = 0) AND t.tid != 0 ORDER BY weight, name;
SELECT t.word AS realword, i.word FROM search_total t LEFT JOIN search_index i ON t.word = i.word WHERE i.word IS NULL;
SELECT type, title FROM menu WHERE mid = 0;
SELECT u.* FROM users u WHERE u.uid = 0;
SELECT uid FROM authmap WHERE authname = '%s';
SELECT uid FROM users WHERE data = '%profile%';
SELECT uid FROM users WHERE uid > 0;
SELECT uid, vote FROM queue WHERE nid = 0;
SELECT v.mid, v.vote, MAX(v.weight) AS weight, MAX(r.value) AS value FROM moderation_votes v INNER JOIN moderation_roles r ON r.mid = v.mid WHERE r.rid IN (0,1) GROUP BY v.mid, v.vote ORDER BY weight;
SELECT v.*, n.type FROM vocabulary v LEFT JOIN vocabulary_node_types n ON v.vid = n.vid ORDER BY v.weight, v.name;
SELECT v.*, n.type FROM vocabulary v LEFT JOIN vocabulary_node_types n ON v.vid = n.vid WHERE n.type = '%s' ORDER BY v.weight, v.name;
SELECT v.*, n.type FROM vocabulary v LEFT JOIN vocabulary_node_types n ON v.vid = n.vid WHERE v.vid = 0 ORDER BY v.weight, v.name;
SELECT w.*, u.name, u.uid FROM watchdog w INNER JOIN users u ON w.uid = u.uid WHERE w.wid = 0;
SELECT COUNT(c.cid) FROM node n INNER JOIN comments c ON n.nid = c.nid WHERE n.nid = 0 AND timestamp > 0 AND c.status = 0;
SELECT n.nid, n.created FROM node n WHERE n.type = 'blog' AND n.status = 1 ORDER BY n.created DESC;
SELECT n.nid, n.sticky, n.created FROM node n WHERE n.promote = 1 AND n.status = 1 ORDER BY n.sticky DESC, n.created DESC;
SELECT n.nid, n.sticky, n.created FROM node n WHERE type = 'blog' AND n.uid = 0 AND n.status = 1 ORDER BY n.sticky DESC, n.created DESC;
SELECT COUNT(*) FROM comments WHERE status = 0 AND nid = 0;
SELECT a.aid, a.timestamp, a.url, a.uid, u.name FROM accesslog a LEFT JOIN users u ON a.uid = u.uid WHERE a.path = 'node/%d%%';
SELECT aid, timestamp, path, title FROM accesslog WHERE uid = 0;
SELECT * FROM users WHERE LOWER(name) = LOWER('%%%s%%');
SELECT uid, changed FROM users WHERE uid > 0 ORDER BY changed DESC;
SELECT u.uid, u.changed FROM users u INNER JOIN profile_values v ON u.uid = v.uid WHERE v.fid = 0 ORDER BY u.changed DESC;
SELECT f.nid FROM forum f WHERE f.tid = 0;
SELECT n.nid, n.changed, NULL, 0, 0 FROM node n;
SELECT * FROM aggregator_category WHERE cid = 0;
SELECT * FROM aggregator_feed WHERE fid = 0;
SELECT * FROM boxes WHERE bid = 0;
SELECT * FROM url_alias WHERE pid = 0;
SELECT last_comment_timestamp, last_comment_name, comment_count FROM node_comment_statistics WHERE nid = 0;
SELECT * FROM term_data WHERE tid = 0;
SELECT * FROM term_synonym s, term_data t WHERE t.tid = s.tid AND s.name = '%s';
SELECT n.nid, n.title, u.uid, u.name FROM node_counter s INNER JOIN node n ON s.nid = n.nid INNER JOIN users u ON n.uid = u.uid WHERE n.status = 1; 
SELECT rid FROM role WHERE name = 'authenticated user';
SELECT * FROM role WHERE rid = 0;
SELECT r.name FROM role r INNER JOIN users_roles ur ON ur.rid = r.rid WHERE ur.uid = 0;
SELECT nid,tid FROM forum WHERE shadow=0;
SELECT COUNT((path)) FROM accesslog;
SELECT COUNT((uid)) FROM accesslog;
SELECT COUNT(n.nid) FROM node n INNER JOIN queue q ON n.nid = q.nid WHERE n.moderate = 1;
SELECT COUNT(n.nid) FROM node n INNER JOIN term_node r ON n.nid = r.nid AND r.tid = 0 WHERE n.status = 1 AND n.type = 'forum';
SELECT COUNT((n.nid)) FROM node n INNER JOIN term_node tn ON n.nid = tn.nid WHERE tn.tid IN (0,1) AND n.status = 1;
SELECT COUNT((n.nid)) FROM node n LEFT JOIN comments c ON n.nid = c.nid AND (c.status = 0 OR c.status IS NULL) WHERE n.status = 1 AND (n.uid = 0 OR c.uid = 0);
SELECT COUNT(n.nid) FROM node n WHERE n.status = 1;
SELECT MAX(n.created) FROM node n INNER JOIN poll p ON p.nid = n.nid WHERE n.status = 1 AND p.active = 1 AND n.moderate = 0;
SELECT n.nid, n.title, l.comment_count FROM node n INNER JOIN node_comment_statistics l ON n.nid = l.nid WHERE n.type = 'forum' AND n.status = 1 ORDER BY n.nid DESC;
SELECT n.nid, n.title, l.last_comment_timestamp, l.comment_count FROM node n INNER JOIN node_comment_statistics l ON n.nid = l.nid WHERE n.status = 1 AND n.type='forum' ORDER BY l.last_comment_timestamp DESC;
SELECT a.aid, a.path, a.title, a.uid, u.name, a.timestamp FROM accesslog a LEFT JOIN users u ON u.uid = a.uid;
SELECT COUNT(a.uid) AS hits, a.uid, u.name FROM accesslog a LEFT JOIN users u ON a.uid = u.uid GROUP BY a.uid, u.name;
SELECT COUNT(*) FROM node_access WHERE nid = 0 AND realm IN (0,1) AND gid IN (0,1);
SELECT COUNT(*) FROM node_access WHERE (nid = 0 OR nid = 0) AND realm IN (0,1) AND gid IN (0,1);
SELECT COUNT(n.nid) FROM node n INNER JOIN history h ON n.nid = h.nid AND h.uid = 0 INNER JOIN term_node r ON n.nid = r.nid AND r.tid = 0 WHERE n.status = 1 AND n.type = 'forum' AND n.created > 0;
SELECT COUNT(n.nid) FROM node n INNER JOIN term_node r ON n.nid = r.nid AND r.tid = 0 WHERE n.created <= 0 AND n.status = 1 AND n.type = 'forum';
SELECT COUNT(path) AS hits, path, title FROM accesslog GROUP BY path, title;
SELECT c.subject, c.nid, c.cid, c.comment, c.timestamp, c.status, c.name, c.homepage, u.name AS registered_name, u.uid FROM comments c INNER JOIN users u ON u.uid = c.uid WHERE c.status = 'sth';
SELECT (n.nid), n.sticky, n.title, n.created FROM node n INNER JOIN term_node tn ON n.nid = tn.nid WHERE tn.tid IN (0,1) AND n.status = 1 ORDER BY n.sticky DESC, n.created DESC;
SELECT (n.nid), n.title, n.type, n.changed, n.uid, u.name, l.last_comment_timestamp AS last_post, l.comment_count FROM node n INNER JOIN node_comment_statistics l ON n.nid = l.nid INNER JOIN users u ON n.uid = u.uid LEFT JOIN comments c ON n.nid = c.nid AND (c.status = 0 OR c.status IS NULL) WHERE n.status = 1 AND (n.uid = 0 OR c.uid = 0) ORDER BY last_post DESC;
SELECT (n.nid), n.title, n.type, n.changed, n.uid, u.name, l.last_comment_timestamp AS last_post, l.comment_count FROM node n INNER JOIN users u ON n.uid = u.uid INNER JOIN node_comment_statistics l ON n.nid = l.nid WHERE n.status = 1 ORDER BY last_post DESC;
SELECT * FROM url_alias;
SELECT n.nid FROM node n LEFT JOIN history h ON n.nid = h.nid AND h.uid = 0 INNER JOIN term_node r ON n.nid = r.nid AND r.tid = 0 WHERE n.status = 1 AND n.type = 'forum' AND h.nid IS NULL AND n.created > 0 ORDER BY created;
SELECT n.nid, n.created FROM node n WHERE n.status = 1 AND n.created > 0 AND n.created < 0 ORDER BY n.created;
SELECT n.nid, n.created FROM node n WHERE n.status = 1 AND n.created > 0 AND n.created < 0 ORDER BY n.created;
SELECT n.nid, n.title, n.sticky, l.comment_count, l.last_comment_timestamp FROM node n INNER JOIN node_comment_statistics l ON n.nid = l.nid INNER JOIN term_node r ON n.nid = r.nid AND r.tid = 0 WHERE n.status = 1 AND n.type = 'forum' ORDER BY n.sticky DESC;
SELECT n.nid, n.title, p.active, n.created, SUM(c.chvotes) AS votes FROM node n INNER JOIN poll p ON n.nid = p.nid INNER JOIN poll_choices c ON n.nid = c.nid WHERE n.status = 1 AND n.moderate = 0 GROUP BY n.nid, n.title, p.active, n.created ORDER BY n.created DESC;
SELECT r.tid, COUNT(n.nid) AS topic_count, SUM(l.comment_count) AS comment_count FROM node n INNER JOIN node_comment_statistics l ON n.nid = l.nid INNER JOIN term_node r ON n.nid = r.nid WHERE n.status = 1 AND n.type = 'forum' GROUP BY r.tid;
SELECT u.uid, u.name, u.status, u.changed FROM users u WHERE uid != 0;
SELECT w.*, u.name, u.uid FROM watchdog w INNER JOIN users u ON w.uid = u.uid;
SELECT totalcount, daycount, timestamp FROM node_counter WHERE nid = 0;
SELECT isdefault, enabled FROM locales_meta WHERE locale = '%s';
SELECT source FROM locales_source WHERE lid = 0;
SELECT COUNT(uid) FROM users WHERE LOWER(name) = '%s';
SELECT minimum FROM moderation_filters WHERE fid = 0;
SELECT MIN(created) FROM node WHERE uid = 0;
SELECT MIN(timestamp) FROM comments WHERE uid = 0;
SELECT title FROM menu WHERE mid = 0;
SELECT title FROM node WHERE nid = 0;
SELECT title FROM node WHERE nid = 0;
SELECT COUNT(*) FROM node WHERE status = 1 AND moderate = 0;
SELECT SUM(score) FROM search_index WHERE word = '%s';
SELECT lid, translation, plid, plural FROM locales_target WHERE lid = 0 AND locale = '%s';
SELECT lid, translation FROM locales_target WHERE lid = 0 AND locale = '%s';
SELECT translation FROM locales_target WHERE lid = 0 AND locale = '%s';
SELECT COUNT(*) AS translation FROM locales_target WHERE locale = '%s' AND translation != '';
SELECT (uid), MAX(timestamp) AS max_timestamp FROM sessions WHERE timestamp >= 0 AND uid != 0 GROUP BY uid ORDER BY max_timestamp DESC;
SELECT COUNT((uid)) AS cnt FROM sessions WHERE timestamp >= 0 AND uid != 0 GROUP BY uid ORDER BY timestamp DESC;
SELECT MAX(uid) FROM users;
SELECT block FROM aggregator_category WHERE cid = 0;
SELECT block FROM aggregator_feed WHERE fid = 0;a
SELECT vid FROM vocabulary WHERE module='%s';
SELECT vote, weight FROM moderation_votes WHERE mid = 0;
SELECT weight FROM book WHERE nid = 0;