SELECT COUNT(dst) FROM url_alias WHERE dst = '%s';
SELECT * FROM access WHERE status = 1 AND type = '%s' AND LOWER('%s') = LOWER(mask);
SELECT * FROM users WHERE status = 1 AND name = LOWER('%s');
SELECT * FROM boxes WHERE bid = 0;
SELECT * FROM book WHERE vid = 0;
SELECT * FROM book WHERE vid = 0;
SELECT data, created, headers, expire FROM cache WHERE cid = '%s';
SELECT cache FROM filter_formats WHERE format = 0;
SELECT comment_count FROM node_comment_statistics WHERE nid = 0;
SELECT COUNT(cid) FROM comments WHERE pid = 0 AND status = 0;
SELECT c.cid, c.title, f.fid FROM aggregator_category c LEFT JOIN aggregator_category_feed f ON c.cid = f.cid AND f.fid = 0 ORDER BY title;
SELECT cid FROM aggregator_category_feed WHERE fid = 0;
SELECT c.cid, c.title, ci.iid FROM aggregator_category c LEFT JOIN aggregator_category_item ci ON c.cid = ci.cid AND ci.iid = 0;
SELECT cid FROM aggregator_category WHERE title = '%s' AND cid != 0;
SELECT cid FROM aggregator_category WHERE title = '%s';
SELECT cid, title FROM aggregator_category WHERE cid = 0;
SELECT cid, title FROM aggregator_category WHERE cid = 0;
SELECT v.* FROM vocabulary v INNER JOIN vocabulary_node_types n ON v.vid = n.vid WHERE n.type = '%s' ORDER BY v.weight, v.name;
SELECT n.nid, n.title, b.weight FROM node n INNER JOIN book b ON n.vid = b.vid WHERE b.parent = 0 AND n.status = 1 AND n.moderate = 0 ORDER BY b.weight ASC, n.title ASC;
SELECT n.nid, n.title, b.weight FROM node n INNER JOIN book b ON n.vid = b.vid WHERE b.parent = 0 ORDER BY b.weight, n.title;
SELECT n.nid, n.title, b.weight FROM node n INNER JOIN book b ON n.vid = b.vid WHERE n.status = 1 AND b.parent = 0 AND n.moderate = 0 ORDER BY b.weight, n.title;
SELECT c.*, u.name AS registered_name, u.uid FROM comments c INNER JOIN users u ON u.uid = c.uid WHERE c.cid = 0;
SELECT c.*, u.uid, u.name AS registered_name, u.data FROM comments c INNER JOIN users u ON c.uid = u.uid WHERE c.cid = 0;
SELECT c.*, u.uid, u.name AS registered_name, u.picture, u.data FROM comments c INNER JOIN users u ON c.uid = u.uid WHERE c.cid = 0 AND c.status = 0;
SELECT comment FROM node WHERE nid = 0;
SELECT subject, comment, format FROM comments WHERE nid = 0 AND status = 0;
SELECT comment_count FROM node_comment_statistics WHERE nid = 0;
SELECT * FROM contact WHERE cid = 0;
SELECT COUNT(cid) FROM comments WHERE nid = 0 AND status = 0;
SELECT COUNT(cid) FROM comments WHERE nid = 0 AND status = 0;
SELECT COUNT(fid) FROM file_revisions WHERE fid = 0;
SELECT COUNT(fid) FROM file_revisions WHERE fid = 0;
SELECT COUNT(pid) FROM url_alias;
SELECT count(n.nid) FROM node n WHERE n.status = 1 AND n.created > 0 AND n.created < 0 ORDER BY n.created;
SELECT data FROM users WHERE uid = 0;
SELECT t.tid, t.* FROM term_data t WHERE LOWER('%s') = LOWER(t.name);
SELECT * FROM access WHERE status = 0 AND type = '%s' AND LOWER('%s') = LOWER(mask);
SELECT * FROM users WHERE status = 0 AND name = LOWER('%s');
SELECT n.nid, n.title, b.weight FROM node n INNER JOIN book b ON n.vid = b.vid WHERE b.parent = 0 AND n.status = 1 AND n.moderate = 0 AND (b.weight < 0 OR (b.weight = 0 AND n.title < '%s')) ORDER BY b.weight DESC, n.title DESC;
SELECT COUNT(cid) FROM comments WHERE pid = 0 AND nid = 0 AND subject = '%s' AND comment = '%s';
SELECT aid, type, status, mask FROM access WHERE aid = 0;
SELECT * FROM contact WHERE cid = 0;
SELECT * FROM profile_fields WHERE fid = 0;
SELECT pages, visibility, custom FROM blocks WHERE module = '%s' AND delta = '%s';
SELECT aid, type, status, mask FROM access WHERE aid = 0;
SELECT uid FROM users WHERE uid != 0 AND LOWER(mail) = LOWER('%s');
SELECT uid FROM users WHERE uid != 0 AND LOWER(name) = LOWER('%s');
SELECT COUNT(dst) FROM url_alias WHERE dst = '%s' AND src != '%s';
SELECT nid FROM node WHERE nid = 0;
SELECT nid FROM node WHERE nid = 0;
SELECT filename FROM system WHERE name = '%s' AND type = '%s';
SELECT hostname FROM poll_votes WHERE nid = 0 AND hostname = '%s';
SELECT iid FROM aggregator_item WHERE fid = 0 AND link = '%s';
SELECT iid FROM aggregator_item WHERE fid = 0 AND title = '%s';
SELECT * FROM aggregator_feed WHERE fid = 0;
SELECT (fid), type, title, page, visibility FROM profile_fields WHERE name = '%s';
SELECT title FROM profile_fields WHERE fid = 0;
SELECT * FROM filter_formats WHERE format = 0;
SELECT * FROM filter_formats WHERE format = 0;
SELECT * FROM forum WHERE vid = 0;
SELECT COUNT(sid) as cnt FROM sessions WHERE timestamp >= 0 AND uid = 0;
SELECT COUNT(sid) as cnt FROM sessions WHERE timestamp >= 0 AND uid = 0;
SELECT timestamp FROM history WHERE uid = 0 AND nid = 0;
SELECT id FROM sequences WHERE name = '%s';
SELECT id FROM sequences WHERE name = '%s';
SELECT dst FROM url_alias WHERE src = '%s';
SELECT cid, title, block FROM aggregator_category WHERE cid = 0;
SELECT c.*, u.uid, u.name AS registered_name, u.picture, u.data FROM comments c INNER JOIN users u ON c.uid = u.uid WHERE c.cid = 0 AND c.status = 0;
SELECT locale FROM locales_meta WHERE locale = '%s';
SELECT module FROM blocks WHERE theme = '%s';
SELECT nid FROM node WHERE status = 1 AND moderate = 0 AND (created > 'variable' OR changed > 'variable');
SELECT status FROM system WHERE type = 'theme' AND name = '%s' AND status = 0;
SELECT COUNT(dst) FROM url_alias WHERE pid != 0 AND dst = '%s';
SELECT COUNT(*) FROM filters WHERE format = 0;
SELECT COUNT(*) FROM role WHERE name = '%s' AND rid != 0;
SELECT COUNT(*) FROM role WHERE name = '%s';
SELECT COUNT(*) FROM term_data WHERE tid = 0 AND vid = 0;
SELECT COUNT(vid) FROM node_revisions WHERE nid = 0;
SELECT COUNT(vid) FROM node_revisions WHERE nid = 0;
SELECT fid FROM profile_fields WHERE name = '%s';
SELECT fid FROM profile_fields WHERE title = '%s' AND category = '%s';
SELECT locale FROM locales_meta WHERE locale = '%s';
SELECT info FROM boxes WHERE info = '%s';
SELECT fid, title, block FROM aggregator_feed WHERE fid = 0;
SELECT i.*, f.title as ftitle, f.link as flink FROM aggregator_item i, aggregator_feed f WHERE i.iid = 0 AND i.fid = f.fid;
SELECT category FROM contact WHERE cid = 0;
SELECT title FROM menu WHERE mid = 0;
SELECT * FROM menu WHERE mid = 0;
SELECT * FROM menu WHERE mid = 0;
SELECT type, title FROM menu WHERE mid = 0;
SELECT src FROM url_alias WHERE dst = '%s';
SELECT uid FROM poll_votes WHERE nid = 0 AND uid = 0;
SELECT * FROM menu WHERE path = 'node/0';
SELECT i.title, i.timestamp, i.link FROM aggregator_item i WHERE i.fid = 0 ORDER BY i.timestamp DESC;
SELECT i.title, i.timestamp, i.link, f.title as feed_title, f.link as feed_link FROM aggregator_category_item ci LEFT JOIN aggregator_item i ON i.iid = ci.iid LEFT JOIN aggregator_feed f ON i.fid = f.fid WHERE ci.cid = 0 ORDER BY i.timestamp DESC;
SELECT s.source, s.location, s.lid, t.translation, t.locale FROM locales_source s INNER JOIN locales_target t ON s.lid = t.lid ;
SELECT max(wid) AS wid FROM watchdog;
SELECT n.nid, n.title, b.parent, b.weight FROM node n INNER JOIN book b ON n.vid = b.vid WHERE n.status = 1 AND b.parent = 0 ORDER BY b.weight DESC, n.title DESC;
SELECT cid, name, timestamp, uid FROM comments WHERE nid = 0 AND status = 0 ORDER BY cid DESC;
SELECT lid FROM locales_source WHERE source = '%s';
SELECT lid FROM locales_source WHERE source = '%s';
SELECT lid FROM locales_source WHERE source = '%s';
SELECT lid FROM locales_source WHERE source = '%s';
SELECT lid FROM locales_source WHERE source = '%s';
SELECT MAX(thread) FROM comments WHERE nid = 0;
SELECT MAX(thread) FROM comments WHERE thread = '%s.%%' AND nid = 0;
SELECT * FROM locales_meta WHERE locale = '%s';
SELECT n.nid, n.title, b.weight FROM node n INNER JOIN book b ON n.vid = b.vid WHERE b.parent = 0 AND n.status = 1 AND n.moderate = 0 AND (b.weight > 0 OR (b.weight = 0 AND n.title > '%s')) ORDER BY b.weight ASC, n.title ASC;
SELECT changed FROM node WHERE nid = 0;
SELECT n.nid, n.vid, n.type, n.status, n.created, n.changed, n.comment, n.promote, n.moderate, n.sticky, r.timestamp AS revision_timestamp, r.title, r.body, r.teaser, r.log, r.format, u.uid, u.name, u.picture, u.data FROM node n INNER JOIN users u ON u.uid = n.uid INNER JOIN node_revisions r ON r.vid = n.vid ;
SELECT n.nid, r.vid, n.type, n.status, n.created, n.changed, n.comment, n.promote, n.moderate, n.sticky, r.timestamp AS revision_timestamp, r.title, r.body, r.teaser, r.log, r.format, u.uid, u.name, u.picture, u.data FROM node n INNER JOIN users u ON u.uid = n.uid INNER JOIN node_revisions r ON r.nid = n.nid AND r.vid = 0 ;
SELECT n.title, n.nid, n.vid, r.format FROM node n INNER JOIN node_revisions r ON n.vid = r.vid WHERE n.nid = 0;
SELECT uid, created FROM node WHERE nid = 0;
SELECT n.nid, n.title, b.parent FROM node n INNER JOIN book b ON n.vid = b.vid WHERE n.nid = 0;
SELECT COUNT(nid) as cnt FROM node;
SELECT n.nid, n.created FROM node n WHERE n.promote = 1 AND n.status = 1 ORDER BY n.created DESC;
SELECT src FROM url_alias WHERE dst = '%s';
SELECT event FROM flood WHERE event = '%s' AND hostname = '%s' AND timestamp > 0;
SELECT tid FROM forum WHERE nid = 0 ORDER BY vid DESC;
SELECT COUNT(*) AS strings FROM locales_source;
SELECT n.nid, n.title, b.parent, b.weight FROM node n INNER JOIN book b ON n.vid = b.vid WHERE n.nid = 0;
SELECT COUNT(src) FROM url_alias WHERE src = '%s';
SELECT runtime, active FROM poll WHERE nid = 0;
SELECT n.nid, n.title FROM node n INNER JOIN book b ON n.vid = b.vid WHERE n.nid = 0 AND n.status = 1 AND n.moderate = 0;
SELECT COUNT((url)) FROM accesslog WHERE url <> '' AND url <>  '%%%s%%';
SELECT COUNT(*) FROM comments WHERE nid = 0;
SELECT c.cid as cid, c.pid, c.nid, c.subject, c.comment, c.format, c.timestamp, c.name, c.mail, c.homepage, u.uid, u.name AS registered_name, u.picture, u.data, c.score, c.users, c.thread, c.status FROM comments c INNER JOIN users u ON c.uid = u.uid WHERE c.nid = 0;
SELECT c.cid, c.pid, c.nid, c.subject, c.comment, c.format, c.timestamp, c.name, c.mail, c.homepage, u.uid, u.name AS registered_name, u.picture, u.data, c.score, c.users, c.status FROM comments c INNER JOIN users u ON c.uid = u.uid WHERE c.cid = 0;
SELECT * FROM filter_formats;
SELECT url, COUNT(url) AS hits, MAX(timestamp) AS last FROM accesslog WHERE url <>  '%%%s%%' AND url <> '' GROUP BY url;
SELECT COUNT(*) FROM node n LEFT JOIN node_comment_statistics c ON n.nid = c.nid WHERE n.status = 1 AND ((n.created = 0 AND n.changed = 0 AND c.last_comment_timestamp = 0 AND n.nid > 0 ) OR (n.created > 0 OR n.changed > 0 OR c.last_comment_timestamp > 0));
SELECT format FROM filter_formats WHERE name='%s';
SELECT MAX(format) AS format FROM filter_formats;
SELECT cid FROM client WHERE link = '%s';
SELECT m.mid, m.* FROM menu m ORDER BY m.mid ASC;
SELECT n.nid FROM node n WHERE n.nid = 0 AND n.type != 'book';
SELECT n.nid, n.title, b.parent, b.weight FROM node n INNER JOIN book b ON n.vid = b.vid WHERE n.status = 1 AND n.moderate = 0 ORDER BY b.weight, n.title;
SELECT n.nid, n.title, b.parent, b.weight FROM node n INNER JOIN book b ON n.vid = b.vid WHERE n.status = 1 ORDER BY b.weight, n.title;
SELECT n.nid, n.title, b.parent FROM node n INNER JOIN book b ON n.vid = b.vid WHERE n.nid = 0;
SELECT n.nid, n.title, b.weight FROM node n INNER JOIN book b ON n.vid = b.vid WHERE b.parent = 0 AND n.status = 1 AND n.moderate = 0 ORDER BY b.weight, n.title;
SELECT n.nid, n.title, b.weight FROM node n INNER JOIN book b ON n.vid = b.vid WHERE b.parent = 0 ORDER BY b.weight, n.title;
SELECT n.nid, n.title, b.weight FROM node n INNER JOIN book b ON n.vid = b.vid WHERE n.status = 1 AND n.nid = 0 AND n.moderate = 0 ORDER BY b.weight, n.title;
SELECT n.nid, n.title, n.status, b.parent FROM node n INNER JOIN book b ON n.vid = b.vid;
SELECT t.* FROM term_data t INNER JOIN term_hierarchy h ON h.tid = t.tid WHERE parent = 0 ORDER BY weight, name;
SELECT t.* FROM term_data t INNER JOIN term_hierarchy h ON h.tid = t.tid WHERE t.vid = 0 AND h.parent = 0 ORDER BY weight, name;
SELECT t.* FROM term_node r INNER JOIN term_data t ON r.tid = t.tid INNER JOIN vocabulary v ON t.vid = v.vid WHERE r.nid = 0 ORDER BY v.weight, t.weight, t.name;
SELECT t.tid, COUNT(n.nid) AS c FROM term_node t INNER JOIN node n ON t.nid = n.nid WHERE n.status = 1 AND n.type = '%s' GROUP BY t.tid;
SELECT t.tid, COUNT(n.nid) AS c FROM term_node t INNER JOIN node n ON t.nid = n.nid WHERE n.status = 1 GROUP BY t.tid;
SELECT t.tid, t.* FROM term_data t INNER JOIN term_hierarchy h ON h.parent = t.tid WHERE h.tid = 0 ORDER BY weight, name;
SELECT t.tid, t.* FROM term_data t INNER JOIN term_node r ON r.tid = t.tid WHERE t.vid = 0 AND r.nid = 0 ORDER BY weight;
SELECT t.tid, t.name FROM term_data t WHERE t.tid IN (0,1);
SELECT t.tid, t.*, parent FROM term_data t INNER JOIN  term_hierarchy h ON t.tid = h.tid WHERE t.vid = 0 ORDER BY weight, name;
SELECT v.*, n.type FROM vocabulary v LEFT JOIN vocabulary_node_types n ON v.vid = n.vid ORDER BY v.weight, v.name;
SELECT v.vid, v.*, n.type FROM vocabulary v LEFT JOIN vocabulary_node_types n ON v.vid = n.vid WHERE n.type = '%s' ORDER BY v.weight, v.name;
SELECT c.nid, c.subject, c.cid, c.timestamp FROM comments c INNER JOIN node n ON n.nid = c.nid WHERE n.status = 1 AND c.status = 0 ORDER BY c.timestamp DESC;
SELECT n.nid, n.title, n.created FROM node n WHERE n.type = 'blog' AND n.status = 1 ORDER BY n.created DESC;

-- SELECT n.nid, n.title, r.teaser, n.created, u.name, u.uid FROM node n INNER JOIN node_revisions r ON n.vid = r.vid INNER JOIN users u ON n.uid = u.uid WHERE n.type = 'blog' AND n.status = 1 ORDER BY n.created DESC;
SELECT ov.nid, ov.title, r.teaser, ov.created, ov.name, ov.uid FROM ourViewN ov INNER JOIN node_revisions r ON ov.vid = r.vid WHERE ov.type = 'blog' AND ov.status = 1 ORDER BY ov.created DESC;

-- SELECT n.nid, n.title, r.teaser, n.created, u.name, u.uid FROM node n INNER JOIN node_revisions r ON n.vid = r.vid INNER JOIN users u ON n.uid = u.uid WHERE n.type = 'blog' AND u.uid = 0 AND n.status = 1 ORDER BY n.created DESC;
SELECT ov.nid, ov.title, r.teaser, ov.created, ov.name, ov.uid FROM ourViewN ov INNER JOIN node_revisions r ON ov.vid = r.vid WHERE ov.type = 'blog' AND ov.uid = 0 AND ov.status = 1 ORDER BY ov.created DESC;

SELECT t.tid, t.name FROM term_data t WHERE t.vid = 0 AND LOWER(t.name) = LOWER('%%%s%%');
SELECT cid, thread FROM comments WHERE cid > 0 ORDER BY cid ASC;
SELECT * FROM aggregator_item WHERE fid = 0 ORDER BY timestamp DESC, iid DESC;
SELECT i.* FROM aggregator_category_item ci LEFT JOIN aggregator_item i ON ci.iid = i.iid WHERE ci.cid = 0 ORDER BY i.timestamp DESC, i.iid DESC;
SELECT name FROM users WHERE LOWER(name) = LOWER('%s%%');

-- SELECT n.nid, n.title, n.created, u.name FROM node n, users u WHERE n.uid = u.uid AND n.type = '%s' AND n.uid = 0 ORDER BY n.created DESC;
SELECT ov.nid, ov.title, ov.created, ov.name FROM ourViewN ov WHERE ov.type = '%s' AND ov.uid = 0 ORDER BY ov.created DESC;

-- SELECT n.nid, n.title, r.body, r.format, n.comment, n.created, u.name FROM node n, node_revisions r, users u WHERE n.uid = u.uid AND n.vid = r.vid AND n.type = '%s' AND n.uid = 0 ORDER BY n.created DESC;
SELECT ov.nid, ov.title, r.body, r.format, ov.comment, ov.created, ov.name FROM node_revisions r, ourViewN ov WHERE ov.vid = r.vid AND ov.type = '%s' AND ov.uid = 0 ORDER BY ov.created DESC;

SELECT uid, name FROM users WHERE status != 0 AND access != 0 ORDER BY created DESC;
SELECT aid, type, status, mask FROM access;
SELECT a.*, u.name FROM accesslog a LEFT JOIN users u ON a.uid = u.uid WHERE aid = 0;
SELECT authname, module FROM authmap WHERE authname = '%s';
SELECT bid, body FROM boxes WHERE format IN (0,1);
SELECT bid, title, info FROM boxes ORDER BY title;
SELECT c.cid, c.title, c.description FROM aggregator_category c LEFT JOIN aggregator_category_item ci ON c.cid = ci.cid LEFT JOIN aggregator_item i ON ci.iid = i.iid GROUP BY c.cid, c.title, c.description;
SELECT c.cid, c.title, count(ci.iid) as items FROM aggregator_category c LEFT JOIN aggregator_category_item ci ON c.cid = ci.cid GROUP BY c.cid, c.title ORDER BY title;
SELECT chtext, chvotes, chorder FROM poll_choices WHERE nid = 0 ORDER BY chorder;
SELECT cid, category, recipients, selected FROM contact ORDER BY weight, category;
SELECT cid, category, selected FROM contact ORDER BY weight, category;
SELECT cid FROM client WHERE changed < 0;
SELECT cid, title FROM aggregator_category ORDER BY title;
SELECT c.nid, c.timestamp, c.name, c.uid, COUNT(c.nid) as comment_count FROM node n LEFT JOIN comments c ON c.nid = n.nid WHERE c.status = 0 GROUP BY c.nid, c.timestamp, c.name, c.uid;
SELECT c.title, c.cid FROM aggregator_category_item ci LEFT JOIN aggregator_category c ON ci.cid = c.cid WHERE ci.iid = 0 ORDER BY c.title;
SELECT c.*, u.name AS registered_name, u.uid FROM comments c INNER JOIN users u ON u.uid = c.uid WHERE pid = 0;
SELECT delta FROM blocks WHERE module = 'aggregator';
SELECT (category) FROM profile_fields;
SELECT (p.perm) FROM role r INNER JOIN permission p ON p.rid = r.rid WHERE r.rid IN (0,1);
SELECT  s.source, t.translation, t.locale FROM locales_source s INNER JOIN locales_target t ON s.lid = t.lid WHERE s.lid = 0;
SELECT (type) FROM watchdog ORDER BY type;
SELECT dst FROM url_alias WHERE src = '%s';
SELECT f.*, COUNT(i.iid) AS items FROM aggregator_feed f LEFT JOIN aggregator_item i ON f.fid = i.fid GROUP BY f.fid, f.title, f.url, f.refresh, f.checked, f.link, f.description, f.etag, f.modified, f.image, f.block ORDER BY f.title;
SELECT f.fid, f.title, f.description, f.image, MAX(i.timestamp) AS last FROM aggregator_feed f LEFT JOIN aggregator_item i ON f.fid = i.fid GROUP BY f.fid, f.title, f.description, f.image ORDER BY last DESC, f.title;
SELECT f.* FROM files f WHERE filepath = '%s';
SELECT fid FROM profile_fields WHERE type = 'textarea';
SELECT fid, name, type FROM profile_fields WHERE LOWER(category) = LOWER('%s') AND visibility != 0;
SELECT fid, name, type FROM profile_fields WHERE register = 1 AND visibility != 0 ORDER BY category, weight;
SELECT fid, title FROM aggregator_feed ORDER BY fid;
SELECT filename, name, type, status, throttle, schema_version FROM system WHERE type = '%s';
SELECT f.name, f.type, v.value FROM profile_fields f INNER JOIN profile_values v ON f.fid = v.fid WHERE uid = 0;
SELECT format FROM filter_formats WHERE name = '%HTML%';
SELECT format FROM filters WHERE module = 'filter' AND delta = 0;
SELECT format FROM filters WHERE module = 'filter' AND delta = 2;
SELECT * FROM aggregator_feed ORDER BY title;
SELECT * FROM aggregator_feed WHERE checked + refresh < 0;
SELECT * FROM blocks WHERE status = 1 AND custom != 0 ORDER BY weight, module, delta;
SELECT * FROM blocks WHERE theme = '%s' AND status = 1 ORDER BY region, weight, module;
SELECT * FROM blocks WHERE theme = '%s';
SELECT * FROM blocks WHERE theme = '%s';
SELECT * FROM client; 
SELECT * FROM files f INNER JOIN file_revisions r ON f.fid = r.fid WHERE r.vid = 0 ORDER BY f.fid;
SELECT * FROM files WHERE nid = 0;
SELECT * FROM filters WHERE format = 0 ORDER BY weight ASC;
SELECT * FROM profile_fields ORDER BY category, weight;
SELECT * FROM profile_fields WHERE LOWER(category) = LOWER('%s') ORDER BY weight;
SELECT * FROM profile_fields WHERE LOWER(category) = LOWER('%s') ORDER BY weight;
SELECT * FROM profile_fields WHERE register = 1 ORDER BY category, weight;
SELECT * FROM profile_fields WHERE register = 1 ORDER BY category, weight;
SELECT * FROM profile_fields WHERE visibility != 0 AND LOWER(category) = LOWER('%s') ORDER BY weight;
SELECT * FROM profile_fields WHERE visibility != 0 AND LOWER(category) = LOWER('%s') ORDER BY weight;
SELECT * FROM profile_fields WHERE visibility != 0 AND register = 1 ORDER BY category, weight;
SELECT * FROM profile_fields WHERE visibility != 0 AND register = 1 ORDER BY category, weight;
SELECT * FROM profile_fields WHERE visibility != 0 AND visibility != 0 ORDER BY category, weight;
SELECT * FROM profile_fields WHERE visibility != 0 ORDER BY category, weight;
SELECT * FROM role;
SELECT * FROM role ORDER BY name;
SELECT * FROM system WHERE type = 'theme';
SELECT * FROM system WHERE type = 'theme_engine' AND status = '1' ORDER BY name;
SELECT * FROM url_alias;
SELECT * FROM users WHERE uid = 1;
SELECT * FROM variable;
SELECT f.title, f.url FROM aggregator_feed f LEFT JOIN aggregator_category_feed c on f.fid = c.fid WHERE c.cid = 0 ORDER BY title;
SELECT iid FROM aggregator_item WHERE fid = 0 AND timestamp < 0;
SELECT iid FROM aggregator_item WHERE fid = 0;
SELECT iid FROM aggregator_item WHERE fid = 0;
SELECT lid FROM locales_source;
SELECT lid, source FROM locales_source WHERE source = '%s';
SELECT locale, name, formula, enabled FROM locales_meta ORDER BY isdefault DESC, enabled DESC, name ASC;
SELECT name, filename, throttle, bootstrap FROM system WHERE type = 'module' AND status = 1 AND bootstrap = 1 ORDER BY weight ASC, filename ASC;
SELECT name, filename, throttle, bootstrap FROM system WHERE type = 'module' AND status = 1 ORDER BY weight ASC, filename ASC;
SELECT name FROM term_synonym WHERE tid = 0;
SELECT name, schema_version FROM system WHERE type = 'module';
SELECT name, title, type, visibility, weight FROM profile_fields WHERE visibility IN (0, 0) ORDER BY weight;
SELECT name, title, type, weight, page FROM profile_fields WHERE fid != 0 AND visibility = 0 ORDER BY weight;
SELECT name, title, type, weight, page FROM profile_fields WHERE visibility = 0 ORDER BY category, weight;
SELECT name, title, weight, visibility FROM profile_fields WHERE visibility IN (0, 0) ORDER BY weight;
SELECT name, type FROM system WHERE status = 1;
SELECT nid, timestamp FROM history WHERE uid = 0;
SELECT pid, src FROM url_alias WHERE src = 'blog/%%';
SELECT p.nid FROM poll p INNER JOIN node n ON p.nid = n.nid WHERE (n.created + p.runtime) < '. time() .' AND p.active = 1 AND p.runtime != 0;
SELECT r.* FROM role r INNER JOIN permission p ON r.rid = p.rid WHERE p.perm = '%%%s%%' ORDER BY r.name;
SELECT rid, name FROM role ORDER BY name;
SELECT rid, name FROM role r WHERE r.rid IN (0,1) ORDER BY name;
SELECT r.rid, p.perm FROM role r LEFT JOIN permission p ON r.rid = p.rid ORDER BY name;
SELECT r.rid, p.perm FROM role r LEFT JOIN permission p ON r.rid = p.rid WHERE r.rid IN (0,1) ORDER BY name;
SELECT r.rid, r.name FROM role r INNER JOIN users_roles ur ON ur.rid = r.rid WHERE ur.uid = 0;
SELECT r.rid, r.name FROM role r INNER JOIN users_roles ur ON ur.rid = r.rid WHERE ur.uid = 0;
SELECT r.vid, r.title, r.log, r.uid, n.vid AS current_vid, r.timestamp, u.name FROM node_revisions r LEFT JOIN node n ON n.vid = r.vid INNER JOIN users u ON u.uid = r.uid WHERE r.nid = 0 ORDER BY r.timestamp DESC;
SELECT sid FROM sessions WHERE sid = '%s';
SELECT sid FROM sessions WHERE sid = '%s';
SELECT s.lid, s.source, s.location, t.plid, t.plural FROM locales_source s INNER JOIN locales_target t ON s.lid = t.lid ORDER BY t.plid, t.plural;
SELECT s.lid, s.source, s.location, t.translation, t.plid, t.plural FROM locales_source s INNER JOIN locales_target t ON s.lid = t.lid WHERE t.locale = '%s' ORDER BY t.plid, t.plural;
SELECT s.lid, t.translation FROM locales_source s INNER JOIN locales_target t ON s.lid = t.lid WHERE s.source = '%s' AND t.locale = '%s';
SELECT s.source, t.translation, t.locale FROM locales_source s INNER JOIN locales_target t ON s.lid = t.lid WHERE t.locale = '%s' AND LENGTH(s.source) < 75;
SELECT tid FROM term_data WHERE vid = 0;
SELECT tid, parent FROM term_hierarchy;
SELECT title, cid FROM aggregator_category ORDER BY title;
SELECT title, url FROM aggregator_feed WHERE (title = '%s' OR url='%s') AND fid != 0;
SELECT title, url FROM aggregator_feed WHERE title = '%s' OR url='%s';
SELECT t.*, tid1, tid2 FROM term_relation, term_data t WHERE (t.tid = tid1 OR t.tid = tid2) AND (tid1 = 0 OR tid2 = 0) AND t.tid != 0 ORDER BY weight, name;
SELECT t.word AS realword, i.word FROM search_total t LEFT JOIN search_index i ON t.word = i.word WHERE i.word IS NULL;
SELECT u.* FROM users u WHERE u.uid = 0;
SELECT uid FROM authmap WHERE authname = '%s';
SELECT u.*, s.* FROM users u INNER JOIN sessions s ON u.uid = s.uid WHERE s.sid = '%s';
SELECT v.*, n.type FROM vocabulary v LEFT JOIN vocabulary_node_types n ON v.vid = n.vid WHERE v.vid = 0 ORDER BY v.weight, v.name;
SELECT w.*, u.name, u.uid FROM watchdog w INNER JOIN users u ON w.uid = u.uid WHERE w.wid = 0;
SELECT COUNT(c.cid) FROM node n INNER JOIN comments c ON n.nid = c.nid WHERE n.nid = 0 AND timestamp > 0 AND c.status = 0;
SELECT n.nid, n.created FROM node n WHERE n.type = 'blog' AND n.status = 1 ORDER BY n.created DESC;
SELECT n.nid, n.sticky, n.created FROM node n WHERE n.promote = 1 AND n.status = 1 ORDER BY n.sticky DESC, n.created DESC;
SELECT n.nid, n.sticky, n.created FROM node n WHERE type = 'blog' AND n.uid = 0 AND n.status = 1 ORDER BY n.sticky DESC, n.created DESC;
SELECT a.aid, a.timestamp, a.url, a.uid, u.name FROM accesslog a LEFT JOIN users u ON a.uid = u.uid WHERE a.path = 'node/0%%';
SELECT aid, timestamp, path, title FROM accesslog WHERE uid = 0;
SELECT c.subject, c.nid, c.cid, c.comment, c.timestamp, c.status, c.name, c.homepage, u.name AS registered_name, u.uid FROM comments c INNER JOIN users u ON u.uid = c.uid WHERE c.status = 0;
SELECT * FROM users WHERE LOWER(name) = LOWER('%%%s%%');
SELECT uid, access FROM users WHERE uid > 0 AND status != 0 AND access != 0 ORDER BY access DESC;
SELECT u.uid, u.access FROM users u INNER JOIN profile_values v ON u.uid = v.uid WHERE v.fid = 0 AND u.access != 0 AND u.status != 0 ORDER BY u.access DESC; 
SELECT f.nid FROM forum f WHERE f.tid = 0;
SELECT * FROM files;
SELECT * FROM files;
SELECT n.nid, n.changed, NULL, 0, 0 FROM node n;
SELECT * FROM aggregator_item WHERE fid = 0 ORDER BY timestamp DESC, iid DESC;
SELECT i.*, f.title AS ftitle, f.link AS flink FROM aggregator_category_item c LEFT JOIN aggregator_item i ON c.iid = i.iid LEFT JOIN aggregator_feed f ON i.fid = f.fid WHERE cid = 0 ORDER BY timestamp DESC, iid DESC;
SELECT i.*, f.title AS ftitle, f.link AS flink FROM aggregator_item i INNER JOIN aggregator_feed f ON i.fid = f.fid ORDER BY i.timestamp DESC, i.iid DESC;
SELECT * FROM aggregator_category WHERE cid = 0;
SELECT * FROM aggregator_feed WHERE fid = 0;
SELECT * FROM boxes WHERE bid = 0;
SELECT * FROM url_alias WHERE pid = 0;
SELECT last_comment_timestamp, last_comment_name, comment_count FROM node_comment_statistics WHERE nid = 0;
SELECT * FROM comments WHERE cid = 0;
SELECT * FROM term_data WHERE tid = 0;
SELECT * FROM term_synonym s, term_data t WHERE t.tid = s.tid AND s.name = '%s';

-- SELECT n.nid, n.title, u.uid, u.name FROM node n INNER JOIN node_counter s ON n.nid = s.nid INNER JOIN users u ON n.uid = u.uid WHERE n.status = 1; 
SELECT ov.nid, ov.title, ov.uid, ov.name FROM node_counter s INNER JOIN ourViewN ov ON s.nid = ov.nid WHERE ov.status = 1; 

SELECT SUM(filesize) FROM files;
SELECT SUM(filesize) FROM files f INNER JOIN node n ON f.nid = n.nid WHERE n.uid = 0;
SELECT COUNT(vid) FROM node_revisions WHERE nid = 0;
SELECT * FROM role WHERE rid = 0;
SELECT * FROM system;
SELECT MAX(cid) FROM comments
SELECT MAX(cid) FROM comments WHERE format IN (0,1);
SELECT MAX(vid) FROM node_revisions WHERE format IN (0,1);
SELECT MAX(uid) FROM profile_values WHERE fid IN (0,1);
SELECT COUNT((path)) FROM accesslog;
SELECT COUNT((uid)) FROM accesslog;
SELECT COUNT(n.nid) FROM node n INNER JOIN term_node r ON n.nid = r.nid AND r.tid = 0 WHERE n.status = 1 AND n.type = 'forum';
SELECT COUNT((n.nid)) FROM node n INNER JOIN term_node tn ON n.nid = tn.nid WHERE tn.tid IN (0,1) AND n.status = 1 AND n.moderate = 0;
SELECT COUNT((n.nid)) FROM node n LEFT JOIN comments c ON n.nid = c.nid AND (c.status = 0 OR c.status IS NULL) WHERE n.status = 1 AND (n.uid = 0 OR c.uid = 0);
SELECT COUNT(n.nid) FROM node n WHERE n.status = 1;
SELECT MAX(n.created) FROM node n INNER JOIN poll p ON p.nid = n.nid WHERE n.status = 1 AND p.active = 1 AND n.moderate = 0;
SELECT n.nid, n.created FROM node n WHERE n.status = 1 AND n.created > 0 AND n.created < 0 ORDER BY n.created;
SELECT n.nid, n.title, l.comment_count FROM node n INNER JOIN node_comment_statistics l ON n.nid = l.nid WHERE n.status = 1 AND n.type = 'forum' ORDER BY l.last_comment_timestamp DESC;
SELECT n.nid, n.title, l.comment_count FROM node n INNER JOIN node_comment_statistics l ON n.nid = l.nid WHERE n.type = 'forum' AND n.status = 1 ORDER BY n.nid DESC;
SELECT a.aid, a.path, a.title, a.uid, u.name, a.timestamp FROM accesslog a LEFT JOIN users u ON u.uid = a.uid;
SELECT COUNT(a.uid) AS hits, a.uid, u.name, a.hostname, SUM(a.timer) AS total, ac.aid FROM accesslog a LEFT JOIN access ac ON ac.type = 'host' AND LOWER(a.hostname) = (ac.mask) LEFT JOIN users u ON a.uid = u.uid GROUP BY a.hostname, a.uid, u.name, ac.aid;
SELECT COUNT(*) FROM node_access WHERE nid = 0 AND grant_view >= 1;
SELECT COUNT(n.nid) FROM node n INNER JOIN term_node tn ON n.nid = tn.nid AND tn.tid = 0 LEFT JOIN history h ON n.nid = h.nid AND h.uid = 0 WHERE n.status = 1 AND n.type = 'forum' AND n.created > 0 AND h.nid IS NULL;
SELECT COUNT(path) AS hits, path, title, AVG(timer) AS average_time, SUM(timer) AS total_time FROM accesslog GROUP BY path, title;
SELECT (n.nid), n.sticky, n.title, n.created FROM node n INNER JOIN term_node tn ON n.nid = tn.nid WHERE tn.tid IN (0,1) AND n.status = 1 AND n.moderate = 0; 
SELECT (n.nid), n.title, n.type, n.changed, n.uid, u.name, n.changed, l.last_comment_timestamp AS last_updated, l.comment_count FROM node n INNER JOIN node_comment_statistics l ON n.nid = l.nid INNER JOIN users u ON n.uid = u.uid LEFT JOIN comments c ON n.nid = c.nid AND (c.status = 0 OR c.status IS NULL) WHERE n.status = 1 AND (n.uid = 0 OR c.uid = 0) ORDER BY last_updated DESC;

-- SELECT (n.nid), n.title, n.type, n.changed, n.uid, u.name, n.changed, l.last_comment_timestamp AS last_updated, l.comment_count FROM node n INNER JOIN users u ON n.uid = u.uid INNER JOIN node_comment_statistics l ON n.nid = l.nid WHERE n.status = 1 ORDER BY last_updated DESC;
SELECT ov.nid, ov.title, ov.type, ov.changed, ov.uid, ov.name, ov.changed, l.last_comment_timestamp AS last_updated, l.comment_count FROM ourView ov INNER JOIN node_comment_statistics l ON ov.nid = l.nid WHERE ov.status = 1 ORDER BY last_updated DESC;

SELECT * FROM url_alias;
SELECT i.*, f.title AS ftitle, f.link AS flink FROM aggregator_category_item c LEFT JOIN aggregator_item i ON c.iid = i.iid LEFT JOIN aggregator_feed f ON i.fid = f.fid WHERE cid = 0 ORDER BY timestamp DESC, iid DESC;
SELECT i.*, f.title AS ftitle, f.link AS flink FROM aggregator_item i INNER JOIN aggregator_feed f ON i.fid = f.fid ORDER BY i.timestamp DESC, i.iid DESC;
SELECT n.nid FROM node n LEFT JOIN history h ON n.nid = h.nid AND h.uid = 0 INNER JOIN term_node r ON n.nid = r.nid AND r.tid = 0 WHERE n.status = 1 AND n.type = 'forum' AND h.nid IS NULL AND n.created > 0 ORDER BY created;
SELECT n.nid, n.created FROM node n WHERE n.status = 1 AND n.created > 0 AND n.created < 0 ORDER BY n.created;
SELECT n.nid, n.title, n.sticky, l.comment_count, l.last_comment_timestamp FROM node n INNER JOIN node_comment_statistics l ON n.nid = l.nid INNER JOIN term_node r ON n.nid = r.nid AND r.tid = 0 WHERE n.status = 1 AND n.type = 'forum' ORDER BY n.sticky DESC; 
SELECT n.nid, n.title, p.active, n.created, SUM(c.chvotes) AS votes FROM node n INNER JOIN poll p ON n.nid = p.nid INNER JOIN poll_choices c ON n.nid = c.nid WHERE n.status = 1 AND n.moderate = 0 GROUP BY n.nid, n.title, p.active, n.created ORDER BY n.created DESC;
SELECT r.tid, COUNT(n.nid) AS topic_count, SUM(l.comment_count) AS comment_count FROM node n INNER JOIN node_comment_statistics l ON n.nid = l.nid INNER JOIN term_node r ON n.nid = r.nid WHERE n.status = 1 AND n.type = 'forum' GROUP BY r.tid;
SELECT u.uid, u.name, u.status, u.created, u.access FROM users u WHERE uid != 0;
SELECT w.*, u.name, u.uid FROM watchdog w INNER JOIN users u ON w.uid = u.uid;
SELECT totalcount, daycount, timestamp FROM node_counter WHERE nid = 0;
SELECT isdefault, enabled FROM locales_meta WHERE locale = '%s';
SELECT source FROM locales_source WHERE lid = 0;
SELECT subject FROM comments WHERE cid = 0;
SELECT COUNT(uid) FROM users WHERE LOWER(name) = '%s';
SELECT * FROM system WHERE type = 'theme' AND name = '%s';
SELECT title FROM node WHERE nid = 0;
SELECT COUNT(*) FROM node WHERE status = 1;
SELECT SUM(score) FROM search_index WHERE word = '%s';
SELECT lid, translation, plid, plural FROM locales_target WHERE lid = 0 AND locale = '%s';
SELECT lid, translation FROM locales_target WHERE lid = 0 AND locale = '%s';
SELECT translation FROM locales_target WHERE lid = 0 AND locale = '%s';
SELECT COUNT(*) AS translation FROM locales_target WHERE locale = '%s' AND translation != '';
SELECT COUNT(uid) as cnt FROM users;
SELECT uid, name, access FROM users WHERE access >= 0 AND uid != 0 ORDER BY access DESC;
SELECT COUNT((uid)) as cnt FROM sessions WHERE timestamp >= 0 AND uid != 0;
SELECT block FROM aggregator_category WHERE cid = 0;
SELECT block FROM aggregator_feed WHERE fid = 0;
SELECT pid FROM url_alias WHERE dst = '%s';
SELECT MAX(comment_count) FROM node_comment_statistics;
SELECT MAX(totalcount) FROM node_counter;
SELECT vid FROM vocabulary WHERE module = '%s';