 CREATE TABLE  DIAR_CATEGORIES  
   (	 CAT_ID  NUMBER(7,0), 
	 CAT_FIELD  VARCHAR2(4 BYTE), 
	 PED1  VARCHAR2(10 BYTE), 
	 PED2  VARCHAR2(10 BYTE), 
	 PED3  VARCHAR2(10 BYTE), 
	 TABLE_NAME  VARCHAR2(10 BYTE), 
	 YEAR  NUMBER(4,0), 
	 PED4  VARCHAR2(10 BYTE)
   ) ;
   