
  CREATE TABLE   SPR_MHT_DIARDECLN  
   (	 DEN_RES_YEAR  NUMBER(4,0) NOT NULL  , 
	 DEN_RSC_CODE  VARCHAR2(4 BYTE) NOT NULL  , 
	 DEN_GED_CODE  VARCHAR2(2 BYTE) NOT NULL  , 
	 DEN_PRZ_CODE  VARCHAR2(4 BYTE) NOT NULL  , 
	 DEN_PRB_CODE  VARCHAR2(30 BYTE) NOT NULL  , 
	 DEN_CLA_CODE  VARCHAR2(2 BYTE) NOT NULL  , 
	 DEN_LAY_CODE  VARCHAR2(4 BYTE) NOT NULL  , 
	 DEN_SIZE  NUMBER(11,2), 
	 DEN_TOTNUM  NUMBER(9,0), 
	 DEN_SAMPLNUM  NUMBER(6,0), 
	 DEN_YH  NUMBER, 
	 DEN_SE_YH  NUMBER, 
	 DEN_CREATED_BY  VARCHAR2(30 BYTE), 
	 DEN_CHANGED_BY  VARCHAR2(30 BYTE), 
	 DEN_DATE_CREATED  DATE, 
	 DEN_DATE_CHANGED  DATE, 
	 DEN_CELL_ID  NUMBER, 
	 DEN_TYPE_CODE  VARCHAR2(2 BYTE), 
	 DEN_FIRE_FLAG  NUMBER(1,0), 
	 CONSTRAINT  SPR_MHT_DIARDECLN_PK  PRIMARY KEY ( DEN_RES_YEAR ,  DEN_RSC_CODE ,  DEN_GED_CODE ,  DEN_PRZ_CODE ,  DEN_PRB_CODE ,  DEN_CLA_CODE ,  DEN_LAY_CODE )
      
   )   ;
 

   
