
  CREATE TABLE    SPR_VIOKAL_ANAG  
   (	 STRNOMOS  VARCHAR2(3 BYTE), 
	 TYPOS  VARCHAR2(3 BYTE), 
	 NOMOS  VARCHAR2(2 BYTE), 
	 LAY_CODE  NUMBER(1,0), 
	 SYDEL  NUMBER, 
	 NMIN  NUMBER, 
	 STR_CODE  VARCHAR2(4 BYTE)
   )   ;
 
