
create table tmp_REGWORKERS
(
  RGW_RSC_CODE    VARCHAR(4) not null,
  RGW_RES_YEAR    NUMERIC(4) not null,
  RGW_SAM_CODE    VARCHAR(8) not null,
  RGW_AA          NUMERIC(3) not null,
  RGW_SEX         NUMERIC(1),
  RGW_THESH       NUMERIC(1),
  RGW_BORNYEAR    NUMERIC(4),
  RGW_WAGES       NUMERIC(4),
  RGW_FEE         NUMERIC(9),
  CREATED_BY      VARCHAR(30),
  CHANGED_BY      VARCHAR(30),
  DATETIME_CREATED    DATETIME,
  DATETIME_CHANGED    DATETIME,
  RGW_SAM_GEOCODE VARCHAR(8)
)


alter table TMP_REGWORKERS
  add constraint TMP_REGWORKERS_PK primary key (RGW_SAM_CODE, RGW_RES_YEAR, RGW_RSC_CODE, RGW_AA)


alter table TMP_REGWORKERS
  add constraint TMP_REGWORKERS_FK_TMP_SAMPLES foreign key (RGW_RES_YEAR, RGW_RSC_CODE, RGW_SAM_CODE)
  references TMP_SAMPLES (SAM_RES_YEAR, SAM_RSC_CODE, SAM_CODE);