create table tmp_PARTWORKERS
(
  PAW_RSC_CODE    VARCHAR(4) not null,
  PAW_RES_YEAR    NUMERIC(4) not null,
  PAW_SAM_CODE    VARCHAR(8) not null,
  PAW_SEX         NUMERIC(1) not null,
  PAW_PARTIME     NUMERIC(1) not null,
  PAW_PERSONS     NUMERIC(4),
  PAW_WAGES       NUMERIC(6,1),
  PAW_HOURS       NUMERIC(5),
  PAW_FEE         NUMERIC(8),
  CREATED_BY      VARCHAR(30),
  CHANGED_BY      VARCHAR(30),
  DATETIME_CREATED    DATETIME,
  DATETIME_CHANGED    DATETIME,
  PAW_SAM_GEOCODE VARCHAR(8)
)


alter table TMP_PARTWORKERS
  add constraint TMP_PARTWORKERS_PK primary key (PAW_SAM_CODE, PAW_RES_YEAR, PAW_RSC_CODE, PAW_SEX, PAW_PARTIME)
