
create table tmp_HOUSEWORK
(
  HWO_RSC_CODE    VARCHAR(4) not null,
  HWO_RES_YEAR    NUMERIC(4) not null,
  HWO_SAM_CODE    VARCHAR(8) not null,
  HWO_AA          NUMERIC(2) not null,
  HWO_HOLDER      VARCHAR(50),
  HWO_CODE        VARCHAR(2),
  HWO_MELOS       NUMERIC(1),
  HWO_FLAG        NUMERIC(1),
  HWO_SEX         NUMERIC(1),
  HWO_PROF        NUMERIC(1),
  HWO_BORNYEAR    NUMERIC(4),
  HWO_DAYWAGE     NUMERIC(4),
  HWO_OTHER       NUMERIC(1),
  HWO_SECOND      NUMERIC(1),
  HWO_THESH       NUMERIC(1),
  HWO_SECWAGE     NUMERIC(4),
  CREATED_BY      VARCHAR(30),
  CHANGED_BY      VARCHAR(30),
  DATETIME_CREATED    DATETIME,
  DATETIME_CHANGED    DATETIME,
  HWO_SAM_GEOCODE VARCHAR(8)
)


alter table TMP_HOUSEWORK
  add constraint TMP_HWO_PK primary key (HWO_SAM_CODE, HWO_RES_YEAR, HWO_RSC_CODE, HWO_AA)


alter table TMP_HOUSEWORK
  add constraint TMP_HOUSEWORK_FK_TMP_SAMPLES foreign key (HWO_RES_YEAR, HWO_RSC_CODE, HWO_SAM_CODE)
  references TMP_SAMPLES (SAM_RES_YEAR, SAM_RSC_CODE, SAM_CODE);
