create table tmp_OTHERLAND
(
  OLA_RSC_CODE    VARCHAR(4) not null,
  OLA_RES_YEAR    NUMERIC(4) not null,
  OLA_SAM_CODE    VARCHAR(8) not null,
  OLA_CUK_CODE    NUMERIC(2) not null,
  OLA_GEOCODE     VARCHAR(10) not null,
  OLA_ACRES       NUMERIC(8,1),
  CREATED_BY      VARCHAR(30),
  CHANGED_BY      VARCHAR(30),
  DATETIME_CREATED    DATETIME,
  DATETIME_CHANGED    DATETIME,
  OLA_SAM_GEOCODE VARCHAR(8)
)


alter table TMP_OTHERLAND
  add constraint TMP_OTHERLAND_PK primary key (OLA_SAM_CODE, OLA_RES_YEAR, OLA_RSC_CODE, OLA_CUK_CODE, OLA_GEOCODE)


alter table TMP_OTHERLAND
  add constraint TMP_OTHERLAND_FK_SPR_SAMPLES foreign key (OLA_RES_YEAR, OLA_RSC_CODE, OLA_SAM_CODE)
  references TMP_SAMPLES (SAM_RES_YEAR, SAM_RSC_CODE, SAM_CODE)