create table tmp_QUESTAPO
(
  QUD_RSC_CODE  VARCHAR(4) not null,
  QUD_RES_YEAR  NUMERIC(4) not null,
  QUD_SAM_CODE  VARCHAR(8) not null,
  QUD_CAT_ID    NUMERIC(7) not null,
  QUD_NUM       NUMERIC(9,2),
  QUD_PRODNUM   NUMERIC(9,2),
  QUD_WATERED   NUMERIC(9,2),
  QUD_SECONDARY NUMERIC(9,2),
  QUD_GEOCODE   VARCHAR(10),
  QUD_SURFACE   NUMERIC(4),
  QUD_MONTHS    NUMERIC(4),
  CREATED_BY    VARCHAR(30),
  CHANGED_BY    VARCHAR(30),
  DATETIME_CREATED  DATETIME,
  DATETIME_CHANGED  DATETIME,
  QUD_FLAG      NUMERIC(2)
)


alter table tmp_QUESTAPO
  add constraint tmp_QUESTAPO_PK primary key (QUD_RSC_CODE, QUD_RES_YEAR, QUD_SAM_CODE, QUD_CAT_ID)

alter table tmp_QUESTAPO
  add constraint QUD_DIAR_SAMP_FK foreign key (QUD_RES_YEAR, QUD_RSC_CODE, QUD_SAM_CODE)
  references TMP_SAMPLES (SAM_RES_YEAR, SAM_RSC_CODE, SAM_CODE)

 
