SELECT fid, type, title, page, visibility FROM profile_fields WHERE name = '%s';
SELECT name, title, type, weight FROM profile_fields WHERE fid != 0 AND visibility = 0 ORDER BY weight;
SELECT u.uid, u.changed FROM users u INNER JOIN profile_values v ON u.uid = v.uid WHERE v.fid = 0 ORDER BY u.changed DESC; -- AND $query 
SELECT name, title, type, weight FROM profile_fields WHERE visibility = 0 ORDER BY weight;
SELECT uid, changed FROM users WHERE uid > 0 ORDER BY changed DESC;
SELECT f.name, f.type, v.value FROM profile_fields f INNER JOIN profile_values v ON f.fid = v.fid WHERE uid = 0;
SELECT fid, name, type, category, weight FROM profile_fields WHERE register = 1 ORDER BY category, weight;
SELECT fid, name, type FROM profile_fields WHERE LOWER(category) = LOWER('%s');
SELECT * FROM profile_fields ORDER BY category, weight;
SELECT * FROM profile_fields WHERE visibility != 0 ORDER BY category, weight;
SELECT * FROM profile_fields WHERE register = 1 ORDER BY category, weight;
SELECT * FROM profile_fields WHERE LOWER(category) = LOWER('%s') ORDER BY weight;
SELECT * FROM profile_fields WHERE register = 1 ORDER BY category, weight;
SELECT * FROM profile_fields WHERE LOWER(category) = LOWER('%s') ORDER BY weight;
SELECT category FROM profile_fields;
SELECT fid FROM profile_fields WHERE title = '%s' AND category = '%s';
SELECT fid FROM profile_fields WHERE name = '%s';
SELECT * FROM profile_fields WHERE fid = 0;
SELECT * FROM profile_fields ORDER BY category, weight;
