--~ SELECT castsource, casttarget, castcontext FROM pg_cast WHERE castcontext <> 'e' ORDER BY castfunc, 1, 2, 3;
--~ SELECT typoutput FROM pg_type WHERE oid = 0;
--~ SELECT typinput FROM pg_type WHERE oid = 0;
