SELECT n.nid, n.title, COUNT(n.nid) AS comments, MAX(c.timestamp) AS last_comment FROM comments c LEFT JOIN node n ON c.nid = n.nid WHERE c.status = 0 AND c.timestamp > '' AND c.uid = 0 GROUP BY n.nid, n.title ORDER BY last_comment DESC; -- LIMIT 10;
SELECT n.nid, n.title, COUNT(n.nid) AS comments, MAX(c.timestamp) AS last_comment FROM comments c LEFT JOIN node n ON c.nid = n.nid WHERE c.status = 0 AND c.timestamp > '' GROUP BY n.nid, n.title ORDER BY last_comment DESC; -- LIMIT 10;
SELECT c.*, u.name FROM comments c LEFT JOIN users u ON c.uid = u.uid WHERE c.timestamp > 0 AND c.uid = 0 AND c.nid = 0 AND c.status = 0 ORDER BY cid DESC;
SELECT c.*, u.name FROM comments c LEFT JOIN users u ON c.uid = u.uid WHERE c.timestamp > 0 AND c.nid = 0 AND c.status = 0 ORDER BY cid DESC;
